/*
JSNES, based on Jamie Sanders' vNES
Copyright (C) 2010 Ben Firshman

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.
*/
var JSNES=function(a){this.opts={ui:JSNES.DummyUI,swfPath:"lib/",preferredFrameRate:60,fpsInterval:500,showDisplay:!0,emulateSound:!1,sampleRate:44100,CPU_FREQ_NTSC:1789772.5,CPU_FREQ_PAL:1773447.4};if(typeof a!="undefined")for(var b in this.opts)typeof a[b]!="undefined"&&(this.opts[b]=a[b]);this.frameTime=1E3/this.opts.preferredFrameRate;this.ui=new this.opts.ui(this);this.cpu=new JSNES.CPU(this);this.ppu=new JSNES.PPU(this);this.papu=new JSNES.PAPU(this);this.mmap=null;this.keyboard=new JSNES.Keyboard;
this.ui.updateStatus("Ready to load a ROM.")};JSNES.VERSION="c41931c303883dfda315";
JSNES.prototype={isRunning:!1,fpsFrameCount:0,limitFrames:!0,romData:null,reset:function(){this.mmap!==null&&this.mmap.reset();this.cpu.reset();this.ppu.reset();this.papu.reset()},start:function(){var a=this;if(this.rom!==null&&this.rom.valid){if(!this.isRunning)this.isRunning=!0,this.frameInterval=setInterval(function(){a.frame()},this.frameTime/2),this.resetFps(),this.printFps(),this.fpsInterval=setInterval(function(){a.printFps()},this.opts.fpsInterval)}else this.ui.updateStatus("There is no ROM loaded, or it is invalid.")},
frame:function(){this.ppu.startFrame();var a=0,b=this.opts.emulateSound,d=this.cpu,e=this.ppu,f=this.papu;a:for(;;){d.cyclesToHalt===0?(a=d.emulate(),b&&f.clockFrameCounter(a),a*=3):d.cyclesToHalt>8?(a=24,b&&f.clockFrameCounter(8),d.cyclesToHalt-=8):(a=d.cyclesToHalt*3,b&&f.clockFrameCounter(d.cyclesToHalt),d.cyclesToHalt=0);for(;a>0;--a){e.curX===e.spr0HitX&&e.f_spVisibility===1&&e.scanline-21===e.spr0HitY&&e.setStatusFlag(e.STATUS_SPRITE0HIT,!0);if(e.requestEndFrame&&(--e.nmiCounter,e.nmiCounter===
0)){e.requestEndFrame=!1;e.startVBlank();break a}++e.curX;if(e.curX===341)e.curX=0,e.endScanline()}}if(this.limitFrames&&this.lastFrameTime)for(;+new Date-this.lastFrameTime<this.frameTime;);++this.fpsFrameCount;this.lastFrameTime=+new Date},printFps:function(){var a=+new Date,b="Running";this.lastFpsTime&&(b+=": "+(this.fpsFrameCount/((a-this.lastFpsTime)/1E3)).toFixed(2)+" FPS");this.ui.updateStatus(b);this.fpsFrameCount=0;this.lastFpsTime=a},stop:function(){clearInterval(this.frameInterval);clearInterval(this.fpsInterval);
this.isRunning=!1},reloadRom:function(){this.romData!==null&&this.loadRom(this.romData)},loadRom:function(a){this.isRunning&&this.stop();this.ui.updateStatus("Loading ROM...");this.rom=new JSNES.ROM(this);this.rom.load(a);if(this.rom.valid){this.reset();this.mmap=this.rom.createMapper();if(!this.mmap)return;this.mmap.loadROM();this.ppu.setMirroring(this.rom.getMirroringType());this.romData=a;this.ui.updateStatus("Successfully loaded. Ready to be started.")}else this.ui.updateStatus("Invalid ROM!");
return this.rom.valid},resetFps:function(){this.lastFpsTime=null;this.fpsFrameCount=0},setFramerate:function(a){this.opts.preferredFrameRate=a;this.frameTime=1E3/a;this.papu.setSampleRate(this.opts.sampleRate,!1)},setLimitFrames:function(a){this.limitFrames=a;this.lastFrameTime=null},toJSON:function(){return{romData:this.romData,cpu:this.cpu.toJSON(),mmap:this.mmap.toJSON(),ppu:this.ppu.toJSON()}},fromJSON:function(a){this.loadRom(a.romData);this.cpu.fromJSON(a.cpu);this.mmap.fromJSON(a.mmap);this.ppu.fromJSON(a.ppu)}};JSNES.Utils={copyArrayElements:function(a,b,d,e,f){for(var c=0;c<f;++c)d[e+c]=a[b+c]},copyArray:function(a){for(var b=Array(a.length),d=0;d<a.length;++d)b[d]=a[d];return b},fromJSON:function(a,b){for(var d in a.JSON_PROPERTIES)a.JSON_PROPERTIES.hasOwnProperty(d)&&(a[d]=b[a.JSON_PROPERTIES[d]])},toJSON:function(a){var b={},d;for(d in a.JSON_PROPERTIES)a.JSON_PROPERTIES.hasOwnProperty(d)&&(b[a.JSON_PROPERTIES[d]]=a[d]);return b},isIE:function(){return/msie/i.test(navigator.userAgent)&&!/opera/i.test(navigator.userAgent)}};JSNES.CPU=function(a){this.nes=a;this.irqType=this.irqRequested=this.crash=this.cyclesToHalt=this.opdata=this.F_BRK_NEW=this.F_BRK=this.F_NOTUSED_NEW=this.F_NOTUSED=this.F_ZERO=this.F_SIGN=this.F_OVERFLOW=this.F_INTERRUPT_NEW=this.F_INTERRUPT=this.F_DECIMAL=this.F_CARRY=this.REG_STATUS=this.REG_PC_NEW=this.REG_PC=this.REG_SP=this.REG_Y=this.REG_X=this.REG_ACC=this.mem=null;this.reset()};
JSNES.CPU.prototype={IRQ_NORMAL:0,IRQ_NMI:1,IRQ_RESET:2,reset:function(){this.mem=Array(65536);for(var a=0;a<8192;++a)this.mem[a]=255;for(var b=0;b<4;++b)a=b*2048,this.mem[a+8]=247,this.mem[a+9]=239,this.mem[a+10]=223,this.mem[a+15]=191;for(a=8193;a<this.mem.length;++a)this.mem[a]=0;this.REG_Y=this.REG_X=this.REG_ACC=0;this.REG_SP=511;this.REG_PC_NEW=this.REG_PC=32767;this.REG_STATUS=40;this.setStatus(40);this.F_DECIMAL=this.F_CARRY=0;this.F_INTERRUPT_NEW=this.F_INTERRUPT=1;this.F_SIGN=this.F_OVERFLOW=
0;this.F_BRK_NEW=this.F_BRK=this.F_NOTUSED_NEW=this.F_NOTUSED=this.F_ZERO=1;this.opdata=(new JSNES.CPU.OpData).opdata;this.cyclesToHalt=0;this.irqRequested=this.crash=!1;this.irqType=null},emulate:function(){var a,b;if(this.irqRequested){a=this.F_CARRY|(this.F_ZERO===0?1:0)<<1|this.F_INTERRUPT<<2|this.F_DECIMAL<<3|this.F_BRK<<4|this.F_NOTUSED<<5|this.F_OVERFLOW<<6|this.F_SIGN<<7;this.REG_PC_NEW=this.REG_PC;this.F_INTERRUPT_NEW=this.F_INTERRUPT;switch(this.irqType){case 0:if(this.F_INTERRUPT!=0)break;
this.doIrq(a);break;case 1:this.doNonMaskableInterrupt(a);break;case 2:this.doResetInterrupt()}this.REG_PC=this.REG_PC_NEW;this.F_INTERRUPT=this.F_INTERRUPT_NEW;this.F_BRK=this.F_BRK_NEW;this.irqRequested=!1}a=this.opdata[this.nes.mmap.load(this.REG_PC+1)];var d=a>>24;b=0;var e=a>>8&255,f=this.REG_PC;this.REG_PC+=a>>16&255;var c=0;switch(e){case 0:c=this.load(f+2);break;case 1:c=this.load(f+2);c+=c<128?this.REG_PC:this.REG_PC-256;break;case 3:c=this.load16bit(f+2);break;case 4:c=this.REG_ACC;break;
case 5:c=this.REG_PC;break;case 6:c=this.load(f+2)+this.REG_X&255;break;case 7:c=this.load(f+2)+this.REG_Y&255;break;case 8:c=this.load16bit(f+2);(c&65280)!=(c+this.REG_X&65280)&&(b=1);c+=this.REG_X;break;case 9:c=this.load16bit(f+2);(c&65280)!=(c+this.REG_Y&65280)&&(b=1);c+=this.REG_Y;break;case 10:c=this.load(f+2);(c&65280)!=(c+this.REG_X&65280)&&(b=1);c+=this.REG_X;c&=255;c=this.load16bit(c);break;case 11:c=this.load16bit(this.load(f+2));(c&65280)!=(c+this.REG_Y&65280)&&(b=1);c+=this.REG_Y;break;
case 12:c=this.load16bit(f+2),c=c<8191?this.mem[c]+(this.mem[c&65280|(c&255)+1&255]<<8):this.nes.mmap.load(c)+(this.nes.mmap.load(c&65280|(c&255)+1&255)<<8)}c&=65535;switch(a&255){case 0:a=this.REG_ACC+this.load(c)+this.F_CARRY;this.F_OVERFLOW=((this.REG_ACC^this.load(c))&128)==0&&((this.REG_ACC^a)&128)!=0?1:0;this.F_CARRY=a>255?1:0;this.F_SIGN=a>>7&1;this.F_ZERO=a&255;this.REG_ACC=a&255;d+=b;break;case 1:this.REG_ACC&=this.load(c);this.F_SIGN=this.REG_ACC>>7&1;this.F_ZERO=this.REG_ACC;e!=11&&(d+=
b);break;case 2:e==4?(this.F_CARRY=this.REG_ACC>>7&1,this.REG_ACC=this.REG_ACC<<1&255,this.F_SIGN=this.REG_ACC>>7&1,this.F_ZERO=this.REG_ACC):(a=this.load(c),this.F_CARRY=a>>7&1,a=a<<1&255,this.F_SIGN=a>>7&1,this.F_ZERO=a,this.write(c,a));break;case 3:if(this.F_CARRY==0)d+=(f&65280)!=(c&65280)?2:1,this.REG_PC=c;break;case 4:if(this.F_CARRY==1)d+=(f&65280)!=(c&65280)?2:1,this.REG_PC=c;break;case 5:if(this.F_ZERO==0)d+=(f&65280)!=(c&65280)?2:1,this.REG_PC=c;break;case 6:a=this.load(c);this.F_SIGN=a>>
7&1;this.F_OVERFLOW=a>>6&1;a&=this.REG_ACC;this.F_ZERO=a;break;case 7:if(this.F_SIGN==1)++d,this.REG_PC=c;break;case 8:if(this.F_ZERO!=0)d+=(f&65280)!=(c&65280)?2:1,this.REG_PC=c;break;case 9:if(this.F_SIGN==0)d+=(f&65280)!=(c&65280)?2:1,this.REG_PC=c;break;case 10:this.REG_PC+=2;this.push(this.REG_PC>>8&255);this.push(this.REG_PC&255);this.F_BRK=1;this.push(this.F_CARRY|(this.F_ZERO==0?1:0)<<1|this.F_INTERRUPT<<2|this.F_DECIMAL<<3|this.F_BRK<<4|this.F_NOTUSED<<5|this.F_OVERFLOW<<6|this.F_SIGN<<7);
this.F_INTERRUPT=1;this.REG_PC=this.load16bit(65534);--this.REG_PC;break;case 11:if(this.F_OVERFLOW==0)d+=(f&65280)!=(c&65280)?2:1,this.REG_PC=c;break;case 12:if(this.F_OVERFLOW==1)d+=(f&65280)!=(c&65280)?2:1,this.REG_PC=c;break;case 13:this.F_CARRY=0;break;case 14:this.F_DECIMAL=0;break;case 15:this.F_INTERRUPT=0;break;case 16:this.F_OVERFLOW=0;break;case 17:a=this.REG_ACC-this.load(c);this.F_CARRY=a>=0?1:0;this.F_SIGN=a>>7&1;this.F_ZERO=a&255;d+=b;break;case 18:a=this.REG_X-this.load(c);this.F_CARRY=
a>=0?1:0;this.F_SIGN=a>>7&1;this.F_ZERO=a&255;break;case 19:a=this.REG_Y-this.load(c);this.F_CARRY=a>=0?1:0;this.F_SIGN=a>>7&1;this.F_ZERO=a&255;break;case 20:a=this.load(c)-1&255;this.F_SIGN=a>>7&1;this.F_ZERO=a;this.write(c,a);break;case 21:this.REG_X=this.REG_X-1&255;this.F_SIGN=this.REG_X>>7&1;this.F_ZERO=this.REG_X;break;case 22:this.REG_Y=this.REG_Y-1&255;this.F_SIGN=this.REG_Y>>7&1;this.F_ZERO=this.REG_Y;break;case 23:this.REG_ACC=(this.load(c)^this.REG_ACC)&255;this.F_SIGN=this.REG_ACC>>7&
1;this.F_ZERO=this.REG_ACC;d+=b;break;case 24:a=this.load(c)+1&255;this.F_SIGN=a>>7&1;this.F_ZERO=a;this.write(c,a&255);break;case 25:this.REG_X=this.REG_X+1&255;this.F_SIGN=this.REG_X>>7&1;this.F_ZERO=this.REG_X;break;case 26:++this.REG_Y;this.REG_Y&=255;this.F_SIGN=this.REG_Y>>7&1;this.F_ZERO=this.REG_Y;break;case 27:this.REG_PC=c-1;break;case 28:this.push(this.REG_PC>>8&255);this.push(this.REG_PC&255);this.REG_PC=c-1;break;case 29:this.REG_ACC=this.load(c);this.F_SIGN=this.REG_ACC>>7&1;this.F_ZERO=
this.REG_ACC;d+=b;break;case 30:this.REG_X=this.load(c);this.F_SIGN=this.REG_X>>7&1;this.F_ZERO=this.REG_X;d+=b;break;case 31:this.REG_Y=this.load(c);this.F_SIGN=this.REG_Y>>7&1;this.F_ZERO=this.REG_Y;d+=b;break;case 32:e==4?(a=this.REG_ACC&255,this.F_CARRY=a&1,a>>=1,this.REG_ACC=a):(a=this.load(c)&255,this.F_CARRY=a&1,a>>=1,this.write(c,a));this.F_SIGN=0;this.F_ZERO=a;break;case 33:break;case 34:a=(this.load(c)|this.REG_ACC)&255;this.F_SIGN=a>>7&1;this.REG_ACC=this.F_ZERO=a;e!=11&&(d+=b);break;case 35:this.push(this.REG_ACC);
break;case 36:this.F_BRK=1;this.push(this.F_CARRY|(this.F_ZERO==0?1:0)<<1|this.F_INTERRUPT<<2|this.F_DECIMAL<<3|this.F_BRK<<4|this.F_NOTUSED<<5|this.F_OVERFLOW<<6|this.F_SIGN<<7);break;case 37:this.REG_ACC=this.pull();this.F_SIGN=this.REG_ACC>>7&1;this.F_ZERO=this.REG_ACC;break;case 38:a=this.pull();this.F_CARRY=a&1;this.F_ZERO=(a>>1&1)==1?0:1;this.F_INTERRUPT=a>>2&1;this.F_DECIMAL=a>>3&1;this.F_BRK=a>>4&1;this.F_NOTUSED=a>>5&1;this.F_OVERFLOW=a>>6&1;this.F_SIGN=a>>7&1;this.F_NOTUSED=1;break;case 39:e==
4?(a=this.REG_ACC,b=this.F_CARRY,this.F_CARRY=a>>7&1,this.REG_ACC=a=(a<<1&255)+b):(a=this.load(c),b=this.F_CARRY,this.F_CARRY=a>>7&1,a=(a<<1&255)+b,this.write(c,a));this.F_SIGN=a>>7&1;this.F_ZERO=a;break;case 40:e==4?(b=this.F_CARRY<<7,this.F_CARRY=this.REG_ACC&1,this.REG_ACC=a=(this.REG_ACC>>1)+b):(a=this.load(c),b=this.F_CARRY<<7,this.F_CARRY=a&1,a=(a>>1)+b,this.write(c,a));this.F_SIGN=a>>7&1;this.F_ZERO=a;break;case 41:a=this.pull();this.F_CARRY=a&1;this.F_ZERO=(a>>1&1)==0?1:0;this.F_INTERRUPT=
a>>2&1;this.F_DECIMAL=a>>3&1;this.F_BRK=a>>4&1;this.F_NOTUSED=a>>5&1;this.F_OVERFLOW=a>>6&1;this.F_SIGN=a>>7&1;this.REG_PC=this.pull();this.REG_PC+=this.pull()<<8;if(this.REG_PC==65535)return;--this.REG_PC;this.F_NOTUSED=1;break;case 42:this.REG_PC=this.pull();this.REG_PC+=this.pull()<<8;if(this.REG_PC==65535)return;break;case 43:a=this.REG_ACC-this.load(c)-(1-this.F_CARRY);this.F_SIGN=a>>7&1;this.F_ZERO=a&255;this.F_OVERFLOW=((this.REG_ACC^a)&128)!=0&&((this.REG_ACC^this.load(c))&128)!=0?1:0;this.F_CARRY=
a<0?0:1;this.REG_ACC=a&255;e!=11&&(d+=b);break;case 44:this.F_CARRY=1;break;case 45:this.F_DECIMAL=1;break;case 46:this.F_INTERRUPT=1;break;case 47:this.write(c,this.REG_ACC);break;case 48:this.write(c,this.REG_X);break;case 49:this.write(c,this.REG_Y);break;case 50:this.REG_X=this.REG_ACC;this.F_SIGN=this.REG_ACC>>7&1;this.F_ZERO=this.REG_ACC;break;case 51:this.REG_Y=this.REG_ACC;this.F_SIGN=this.REG_ACC>>7&1;this.F_ZERO=this.REG_ACC;break;case 52:this.REG_X=this.REG_SP-256;this.F_SIGN=this.REG_SP>>
7&1;this.F_ZERO=this.REG_X;break;case 53:this.REG_ACC=this.REG_X;this.F_SIGN=this.REG_X>>7&1;this.F_ZERO=this.REG_X;break;case 54:this.REG_SP=this.REG_X+256;this.stackWrap();break;case 55:this.REG_ACC=this.REG_Y;this.F_SIGN=this.REG_Y>>7&1;this.F_ZERO=this.REG_Y;break;default:this.nes.stop(),this.nes.crashMessage="Game crashed, invalid opcode at address $"+f.toString(16)}return d},load:function(a){return a<8192?this.mem[a&2047]:this.nes.mmap.load(a)},load16bit:function(a){return a<8191?this.mem[a&
2047]|this.mem[a+1&2047]<<8:this.nes.mmap.load(a)|this.nes.mmap.load(a+1)<<8},write:function(a,b){a<8192?this.mem[a&2047]=b:this.nes.mmap.write(a,b)},requestIrq:function(a){if(!(this.irqRequested&&a==this.IRQ_NORMAL))this.irqRequested=!0,this.irqType=a},push:function(a){this.nes.mmap.write(this.REG_SP,a);--this.REG_SP;this.REG_SP=256|this.REG_SP&255},stackWrap:function(){this.REG_SP=256|this.REG_SP&255},pull:function(){++this.REG_SP;this.REG_SP=256|this.REG_SP&255;return this.nes.mmap.load(this.REG_SP)},
pageCrossed:function(a,b){return(a&65280)!=(b&65280)},haltCycles:function(a){this.cyclesToHalt+=a},doNonMaskableInterrupt:function(a){if((this.nes.mmap.load(8192)&128)!=0)++this.REG_PC_NEW,this.push(this.REG_PC_NEW>>8&255),this.push(this.REG_PC_NEW&255),this.push(a),this.REG_PC_NEW=this.nes.mmap.load(65530)|this.nes.mmap.load(65531)<<8,--this.REG_PC_NEW},doResetInterrupt:function(){this.REG_PC_NEW=this.nes.mmap.load(65532)|this.nes.mmap.load(65533)<<8;--this.REG_PC_NEW},doIrq:function(a){++this.REG_PC_NEW;
this.push(this.REG_PC_NEW>>8&255);this.push(this.REG_PC_NEW&255);this.push(a);this.F_INTERRUPT_NEW=1;this.F_BRK_NEW=0;this.REG_PC_NEW=this.nes.mmap.load(65534)|this.nes.mmap.load(65535)<<8;--this.REG_PC_NEW},getStatus:function(){return this.F_CARRY|this.F_ZERO<<1|this.F_INTERRUPT<<2|this.F_DECIMAL<<3|this.F_BRK<<4|this.F_NOTUSED<<5|this.F_OVERFLOW<<6|this.F_SIGN<<7},setStatus:function(a){this.F_CARRY=a&1;this.F_ZERO=a>>1&1;this.F_INTERRUPT=a>>2&1;this.F_DECIMAL=a>>3&1;this.F_BRK=a>>4&1;this.F_NOTUSED=
a>>5&1;this.F_OVERFLOW=a>>6&1;this.F_SIGN=a>>7&1},JSON_PROPERTIES:{mem:"mem",cyclesToHalt:"cyclesToHalt",irqRequested:"irqRequested",irqType:"irqType",REG_ACC:"REG_ACC",REG_X:"REG_X",REG_Y:"REG_Y",REG_SP:"REG_SP",REG_PC:"REG_PC",REG_PC_NEW:"REG_PC_NEW",REG_STATUS:"REG_STATUS",F_CARRY:"F_CARRY",F_DECIMAL:"F_DECIMAL",F_INTERRUPT:"F_INTERRUPT",F_INTERRUPT_NEW:"F_INTERRUPT_NEW",F_OVERFLOW:"F_OVERFLOW",F_SIGN:"F_SIGN",F_ZERO:"F_ZERO",F_NOTUSED:"F_NOTUSED",F_NOTUSED_NEW:"F_NOTUSED_NEW",F_BRK:"F_BRK",F_BRK_NEW:"F_BRK_NEW"},
toJSON:function(){return JSNES.Utils.toJSON(this)},fromJSON:function(a){JSNES.Utils.fromJSON(this,a)}};
JSNES.CPU.OpData=function(){this.opdata=Array(256);for(var a=0;a<256;++a)this.opdata[a]=255;this.setOp(this.INS_ADC,105,this.ADDR_IMM,2,2);this.setOp(this.INS_ADC,101,this.ADDR_ZP,2,3);this.setOp(this.INS_ADC,117,this.ADDR_ZPX,2,4);this.setOp(this.INS_ADC,109,this.ADDR_ABS,3,4);this.setOp(this.INS_ADC,125,this.ADDR_ABSX,3,4);this.setOp(this.INS_ADC,121,this.ADDR_ABSY,3,4);this.setOp(this.INS_ADC,97,this.ADDR_PREIDXIND,2,6);this.setOp(this.INS_ADC,113,this.ADDR_POSTIDXIND,2,5);this.setOp(this.INS_AND,
41,this.ADDR_IMM,2,2);this.setOp(this.INS_AND,37,this.ADDR_ZP,2,3);this.setOp(this.INS_AND,53,this.ADDR_ZPX,2,4);this.setOp(this.INS_AND,45,this.ADDR_ABS,3,4);this.setOp(this.INS_AND,61,this.ADDR_ABSX,3,4);this.setOp(this.INS_AND,57,this.ADDR_ABSY,3,4);this.setOp(this.INS_AND,33,this.ADDR_PREIDXIND,2,6);this.setOp(this.INS_AND,49,this.ADDR_POSTIDXIND,2,5);this.setOp(this.INS_ASL,10,this.ADDR_ACC,1,2);this.setOp(this.INS_ASL,6,this.ADDR_ZP,2,5);this.setOp(this.INS_ASL,22,this.ADDR_ZPX,2,6);this.setOp(this.INS_ASL,
14,this.ADDR_ABS,3,6);this.setOp(this.INS_ASL,30,this.ADDR_ABSX,3,7);this.setOp(this.INS_BCC,144,this.ADDR_REL,2,2);this.setOp(this.INS_BCS,176,this.ADDR_REL,2,2);this.setOp(this.INS_BEQ,240,this.ADDR_REL,2,2);this.setOp(this.INS_BIT,36,this.ADDR_ZP,2,3);this.setOp(this.INS_BIT,44,this.ADDR_ABS,3,4);this.setOp(this.INS_BMI,48,this.ADDR_REL,2,2);this.setOp(this.INS_BNE,208,this.ADDR_REL,2,2);this.setOp(this.INS_BPL,16,this.ADDR_REL,2,2);this.setOp(this.INS_BRK,0,this.ADDR_IMP,1,7);this.setOp(this.INS_BVC,
80,this.ADDR_REL,2,2);this.setOp(this.INS_BVS,112,this.ADDR_REL,2,2);this.setOp(this.INS_CLC,24,this.ADDR_IMP,1,2);this.setOp(this.INS_CLD,216,this.ADDR_IMP,1,2);this.setOp(this.INS_CLI,88,this.ADDR_IMP,1,2);this.setOp(this.INS_CLV,184,this.ADDR_IMP,1,2);this.setOp(this.INS_CMP,201,this.ADDR_IMM,2,2);this.setOp(this.INS_CMP,197,this.ADDR_ZP,2,3);this.setOp(this.INS_CMP,213,this.ADDR_ZPX,2,4);this.setOp(this.INS_CMP,205,this.ADDR_ABS,3,4);this.setOp(this.INS_CMP,221,this.ADDR_ABSX,3,4);this.setOp(this.INS_CMP,
217,this.ADDR_ABSY,3,4);this.setOp(this.INS_CMP,193,this.ADDR_PREIDXIND,2,6);this.setOp(this.INS_CMP,209,this.ADDR_POSTIDXIND,2,5);this.setOp(this.INS_CPX,224,this.ADDR_IMM,2,2);this.setOp(this.INS_CPX,228,this.ADDR_ZP,2,3);this.setOp(this.INS_CPX,236,this.ADDR_ABS,3,4);this.setOp(this.INS_CPY,192,this.ADDR_IMM,2,2);this.setOp(this.INS_CPY,196,this.ADDR_ZP,2,3);this.setOp(this.INS_CPY,204,this.ADDR_ABS,3,4);this.setOp(this.INS_DEC,198,this.ADDR_ZP,2,5);this.setOp(this.INS_DEC,214,this.ADDR_ZPX,2,
6);this.setOp(this.INS_DEC,206,this.ADDR_ABS,3,6);this.setOp(this.INS_DEC,222,this.ADDR_ABSX,3,7);this.setOp(this.INS_DEX,202,this.ADDR_IMP,1,2);this.setOp(this.INS_DEY,136,this.ADDR_IMP,1,2);this.setOp(this.INS_EOR,73,this.ADDR_IMM,2,2);this.setOp(this.INS_EOR,69,this.ADDR_ZP,2,3);this.setOp(this.INS_EOR,85,this.ADDR_ZPX,2,4);this.setOp(this.INS_EOR,77,this.ADDR_ABS,3,4);this.setOp(this.INS_EOR,93,this.ADDR_ABSX,3,4);this.setOp(this.INS_EOR,89,this.ADDR_ABSY,3,4);this.setOp(this.INS_EOR,65,this.ADDR_PREIDXIND,
2,6);this.setOp(this.INS_EOR,81,this.ADDR_POSTIDXIND,2,5);this.setOp(this.INS_INC,230,this.ADDR_ZP,2,5);this.setOp(this.INS_INC,246,this.ADDR_ZPX,2,6);this.setOp(this.INS_INC,238,this.ADDR_ABS,3,6);this.setOp(this.INS_INC,254,this.ADDR_ABSX,3,7);this.setOp(this.INS_INX,232,this.ADDR_IMP,1,2);this.setOp(this.INS_INY,200,this.ADDR_IMP,1,2);this.setOp(this.INS_JMP,76,this.ADDR_ABS,3,3);this.setOp(this.INS_JMP,108,this.ADDR_INDABS,3,5);this.setOp(this.INS_JSR,32,this.ADDR_ABS,3,6);this.setOp(this.INS_LDA,
169,this.ADDR_IMM,2,2);this.setOp(this.INS_LDA,165,this.ADDR_ZP,2,3);this.setOp(this.INS_LDA,181,this.ADDR_ZPX,2,4);this.setOp(this.INS_LDA,173,this.ADDR_ABS,3,4);this.setOp(this.INS_LDA,189,this.ADDR_ABSX,3,4);this.setOp(this.INS_LDA,185,this.ADDR_ABSY,3,4);this.setOp(this.INS_LDA,161,this.ADDR_PREIDXIND,2,6);this.setOp(this.INS_LDA,177,this.ADDR_POSTIDXIND,2,5);this.setOp(this.INS_LDX,162,this.ADDR_IMM,2,2);this.setOp(this.INS_LDX,166,this.ADDR_ZP,2,3);this.setOp(this.INS_LDX,182,this.ADDR_ZPY,
2,4);this.setOp(this.INS_LDX,174,this.ADDR_ABS,3,4);this.setOp(this.INS_LDX,190,this.ADDR_ABSY,3,4);this.setOp(this.INS_LDY,160,this.ADDR_IMM,2,2);this.setOp(this.INS_LDY,164,this.ADDR_ZP,2,3);this.setOp(this.INS_LDY,180,this.ADDR_ZPX,2,4);this.setOp(this.INS_LDY,172,this.ADDR_ABS,3,4);this.setOp(this.INS_LDY,188,this.ADDR_ABSX,3,4);this.setOp(this.INS_LSR,74,this.ADDR_ACC,1,2);this.setOp(this.INS_LSR,70,this.ADDR_ZP,2,5);this.setOp(this.INS_LSR,86,this.ADDR_ZPX,2,6);this.setOp(this.INS_LSR,78,this.ADDR_ABS,
3,6);this.setOp(this.INS_LSR,94,this.ADDR_ABSX,3,7);this.setOp(this.INS_NOP,234,this.ADDR_IMP,1,2);this.setOp(this.INS_ORA,9,this.ADDR_IMM,2,2);this.setOp(this.INS_ORA,5,this.ADDR_ZP,2,3);this.setOp(this.INS_ORA,21,this.ADDR_ZPX,2,4);this.setOp(this.INS_ORA,13,this.ADDR_ABS,3,4);this.setOp(this.INS_ORA,29,this.ADDR_ABSX,3,4);this.setOp(this.INS_ORA,25,this.ADDR_ABSY,3,4);this.setOp(this.INS_ORA,1,this.ADDR_PREIDXIND,2,6);this.setOp(this.INS_ORA,17,this.ADDR_POSTIDXIND,2,5);this.setOp(this.INS_PHA,
72,this.ADDR_IMP,1,3);this.setOp(this.INS_PHP,8,this.ADDR_IMP,1,3);this.setOp(this.INS_PLA,104,this.ADDR_IMP,1,4);this.setOp(this.INS_PLP,40,this.ADDR_IMP,1,4);this.setOp(this.INS_ROL,42,this.ADDR_ACC,1,2);this.setOp(this.INS_ROL,38,this.ADDR_ZP,2,5);this.setOp(this.INS_ROL,54,this.ADDR_ZPX,2,6);this.setOp(this.INS_ROL,46,this.ADDR_ABS,3,6);this.setOp(this.INS_ROL,62,this.ADDR_ABSX,3,7);this.setOp(this.INS_ROR,106,this.ADDR_ACC,1,2);this.setOp(this.INS_ROR,102,this.ADDR_ZP,2,5);this.setOp(this.INS_ROR,
118,this.ADDR_ZPX,2,6);this.setOp(this.INS_ROR,110,this.ADDR_ABS,3,6);this.setOp(this.INS_ROR,126,this.ADDR_ABSX,3,7);this.setOp(this.INS_RTI,64,this.ADDR_IMP,1,6);this.setOp(this.INS_RTS,96,this.ADDR_IMP,1,6);this.setOp(this.INS_SBC,233,this.ADDR_IMM,2,2);this.setOp(this.INS_SBC,229,this.ADDR_ZP,2,3);this.setOp(this.INS_SBC,245,this.ADDR_ZPX,2,4);this.setOp(this.INS_SBC,237,this.ADDR_ABS,3,4);this.setOp(this.INS_SBC,253,this.ADDR_ABSX,3,4);this.setOp(this.INS_SBC,249,this.ADDR_ABSY,3,4);this.setOp(this.INS_SBC,
225,this.ADDR_PREIDXIND,2,6);this.setOp(this.INS_SBC,241,this.ADDR_POSTIDXIND,2,5);this.setOp(this.INS_SEC,56,this.ADDR_IMP,1,2);this.setOp(this.INS_SED,248,this.ADDR_IMP,1,2);this.setOp(this.INS_SEI,120,this.ADDR_IMP,1,2);this.setOp(this.INS_STA,133,this.ADDR_ZP,2,3);this.setOp(this.INS_STA,149,this.ADDR_ZPX,2,4);this.setOp(this.INS_STA,141,this.ADDR_ABS,3,4);this.setOp(this.INS_STA,157,this.ADDR_ABSX,3,5);this.setOp(this.INS_STA,153,this.ADDR_ABSY,3,5);this.setOp(this.INS_STA,129,this.ADDR_PREIDXIND,
2,6);this.setOp(this.INS_STA,145,this.ADDR_POSTIDXIND,2,6);this.setOp(this.INS_STX,134,this.ADDR_ZP,2,3);this.setOp(this.INS_STX,150,this.ADDR_ZPY,2,4);this.setOp(this.INS_STX,142,this.ADDR_ABS,3,4);this.setOp(this.INS_STY,132,this.ADDR_ZP,2,3);this.setOp(this.INS_STY,148,this.ADDR_ZPX,2,4);this.setOp(this.INS_STY,140,this.ADDR_ABS,3,4);this.setOp(this.INS_TAX,170,this.ADDR_IMP,1,2);this.setOp(this.INS_TAY,168,this.ADDR_IMP,1,2);this.setOp(this.INS_TSX,186,this.ADDR_IMP,1,2);this.setOp(this.INS_TXA,
138,this.ADDR_IMP,1,2);this.setOp(this.INS_TXS,154,this.ADDR_IMP,1,2);this.setOp(this.INS_TYA,152,this.ADDR_IMP,1,2);this.cycTable=[7,6,2,8,3,3,5,5,3,2,2,2,4,4,6,6,2,5,2,8,4,4,6,6,2,4,2,7,4,4,7,7,6,6,2,8,3,3,5,5,4,2,2,2,4,4,6,6,2,5,2,8,4,4,6,6,2,4,2,7,4,4,7,7,6,6,2,8,3,3,5,5,3,2,2,2,3,4,6,6,2,5,2,8,4,4,6,6,2,4,2,7,4,4,7,7,6,6,2,8,3,3,5,5,4,2,2,2,5,4,6,6,2,5,2,8,4,4,6,6,2,4,2,7,4,4,7,7,2,6,2,6,3,3,3,3,2,2,2,2,4,4,4,4,2,6,2,6,4,4,4,4,2,5,2,5,5,5,5,5,2,6,2,6,3,3,3,3,2,2,2,2,4,4,4,4,2,5,2,5,4,4,4,4,2,
4,2,4,4,4,4,4,2,6,2,8,3,3,5,5,2,2,2,2,4,4,6,6,2,5,2,8,4,4,6,6,2,4,2,7,4,4,7,7,2,6,3,8,3,3,5,5,2,2,2,2,4,4,6,6,2,5,2,8,4,4,6,6,2,4,2,7,4,4,7,7];this.instname=Array(56);this.instname[0]="ADC";this.instname[1]="AND";this.instname[2]="ASL";this.instname[3]="BCC";this.instname[4]="BCS";this.instname[5]="BEQ";this.instname[6]="BIT";this.instname[7]="BMI";this.instname[8]="BNE";this.instname[9]="BPL";this.instname[10]="BRK";this.instname[11]="BVC";this.instname[12]="BVS";this.instname[13]="CLC";this.instname[14]=
"CLD";this.instname[15]="CLI";this.instname[16]="CLV";this.instname[17]="CMP";this.instname[18]="CPX";this.instname[19]="CPY";this.instname[20]="DEC";this.instname[21]="DEX";this.instname[22]="DEY";this.instname[23]="EOR";this.instname[24]="INC";this.instname[25]="INX";this.instname[26]="INY";this.instname[27]="JMP";this.instname[28]="JSR";this.instname[29]="LDA";this.instname[30]="LDX";this.instname[31]="LDY";this.instname[32]="LSR";this.instname[33]="NOP";this.instname[34]="ORA";this.instname[35]=
"PHA";this.instname[36]="PHP";this.instname[37]="PLA";this.instname[38]="PLP";this.instname[39]="ROL";this.instname[40]="ROR";this.instname[41]="RTI";this.instname[42]="RTS";this.instname[43]="SBC";this.instname[44]="SEC";this.instname[45]="SED";this.instname[46]="SEI";this.instname[47]="STA";this.instname[48]="STX";this.instname[49]="STY";this.instname[50]="TAX";this.instname[51]="TAY";this.instname[52]="TSX";this.instname[53]="TXA";this.instname[54]="TXS";this.instname[55]="TYA";this.addrDesc=["Zero Page           ",
"Relative            ","Implied             ","Absolute            ","Accumulator         ","Immediate           ","Zero Page,X         ","Zero Page,Y         ","Absolute,X          ","Absolute,Y          ","Preindexed Indirect ","Postindexed Indirect","Indirect Absolute   "]};
JSNES.CPU.OpData.prototype={INS_ADC:0,INS_AND:1,INS_ASL:2,INS_BCC:3,INS_BCS:4,INS_BEQ:5,INS_BIT:6,INS_BMI:7,INS_BNE:8,INS_BPL:9,INS_BRK:10,INS_BVC:11,INS_BVS:12,INS_CLC:13,INS_CLD:14,INS_CLI:15,INS_CLV:16,INS_CMP:17,INS_CPX:18,INS_CPY:19,INS_DEC:20,INS_DEX:21,INS_DEY:22,INS_EOR:23,INS_INC:24,INS_INX:25,INS_INY:26,INS_JMP:27,INS_JSR:28,INS_LDA:29,INS_LDX:30,INS_LDY:31,INS_LSR:32,INS_NOP:33,INS_ORA:34,INS_PHA:35,INS_PHP:36,INS_PLA:37,INS_PLP:38,INS_ROL:39,INS_ROR:40,INS_RTI:41,INS_RTS:42,INS_SBC:43,
INS_SEC:44,INS_SED:45,INS_SEI:46,INS_STA:47,INS_STX:48,INS_STY:49,INS_TAX:50,INS_TAY:51,INS_TSX:52,INS_TXA:53,INS_TXS:54,INS_TYA:55,INS_DUMMY:56,ADDR_ZP:0,ADDR_REL:1,ADDR_IMP:2,ADDR_ABS:3,ADDR_ACC:4,ADDR_IMM:5,ADDR_ZPX:6,ADDR_ZPY:7,ADDR_ABSX:8,ADDR_ABSY:9,ADDR_PREIDXIND:10,ADDR_POSTIDXIND:11,ADDR_INDABS:12,setOp:function(a,b,d,e,f){this.opdata[b]=a&255|(d&255)<<8|(e&255)<<16|(f&255)<<24}};JSNES.Keyboard=function(){var a;this.keys={KEY_A:0,KEY_B:1,KEY_SELECT:2,KEY_START:3,KEY_UP:4,KEY_DOWN:5,KEY_LEFT:6,KEY_RIGHT:7};this.state1=Array(8);for(a=0;a<this.state1.length;++a)this.state1[a]=64;this.state2=Array(8);for(a=0;a<this.state2.length;++a)this.state2[a]=64};
JSNES.Keyboard.prototype={setKey:function(a,b){switch(a){case 88:this.state1[this.keys.KEY_A]=b;break;case 90:this.state1[this.keys.KEY_B]=b;break;case 17:this.state1[this.keys.KEY_SELECT]=b;break;case 13:this.state1[this.keys.KEY_START]=b;break;case 38:this.state1[this.keys.KEY_UP]=b;break;case 40:this.state1[this.keys.KEY_DOWN]=b;break;case 37:this.state1[this.keys.KEY_LEFT]=b;break;case 39:this.state1[this.keys.KEY_RIGHT]=b;break;case 103:this.state2[this.keys.KEY_A]=b;break;case 105:this.state2[this.keys.KEY_B]=
b;break;case 99:this.state2[this.keys.KEY_SELECT]=b;break;case 97:this.state2[this.keys.KEY_START]=b;break;case 104:this.state2[this.keys.KEY_UP]=b;break;case 98:this.state2[this.keys.KEY_DOWN]=b;break;case 100:this.state2[this.keys.KEY_LEFT]=b;break;case 102:this.state2[this.keys.KEY_RIGHT]=b;break;default:return!0}return!1},keyDown:function(a){!this.setKey(a.keyCode,65)&&a.preventDefault&&a.preventDefault()},keyUp:function(a){!this.setKey(a.keyCode,64)&&a.preventDefault&&a.preventDefault()},keyPress:function(a){a.preventDefault()}};JSNES.Mappers={};JSNES.Mappers[0]=function(a){this.nes=a};
JSNES.Mappers[0].prototype={reset:function(){this.joypadLastWrite=this.joy2StrobeState=this.joy1StrobeState=0;this.mousePressed=!1;this.mouseY=this.mouseX=null},write:function(a,b){a<8192?this.nes.cpu.mem[a&2047]=b:a>16407?this.nes.cpu.mem[a]=b:a>8199&&a<16384?this.regWrite(8192+(a&7),b):this.regWrite(a,b)},writelow:function(a,b){a<8192?this.nes.cpu.mem[a&2047]=b:a>16407?this.nes.cpu.mem[a]=b:a>8199&&a<16384?this.regWrite(8192+(a&7),b):this.regWrite(a,b)},load:function(a){a&=65535;return a>16407?
this.nes.cpu.mem[a]:a>=8192?this.regLoad(a):this.nes.cpu.mem[a&2047]},regLoad:function(a){switch(a>>12){case 2:case 3:switch(a&7){case 0:return this.nes.cpu.mem[8192];case 1:return this.nes.cpu.mem[8193];case 2:return this.nes.ppu.readStatusRegister();case 3:return 0;case 4:return this.nes.ppu.sramLoad();case 5:return 0;case 6:return 0;case 7:return this.nes.ppu.vramLoad()}break;case 4:switch(a-16405){case 0:return this.nes.papu.readReg(a);case 1:return this.joy1Read();case 2:if(this.mousePressed){for(var a=
Math.max(0,this.mouseX-4),b=Math.min(256,this.mouseX+4),d=Math.min(240,this.mouseY+4),e=0,f=Math.max(0,this.mouseY-4);f<d;++f)for(var c=a;c<b;++c)if(this.nes.ppu.buffer[(f<<8)+c]==16777215){e|=8;console.debug("Clicked on white!");break}e|=this.mousePressed?16:0;return(this.joy2Read()|e)&65535}else return this.joy2Read()}}return 0},regWrite:function(a,b){switch(a){case 8192:this.nes.cpu.mem[a]=b;this.nes.ppu.updateControlReg1(b);break;case 8193:this.nes.cpu.mem[a]=b;this.nes.ppu.updateControlReg2(b);
break;case 8195:this.nes.ppu.writeSRAMAddress(b);break;case 8196:this.nes.ppu.sramWrite(b);break;case 8197:this.nes.ppu.scrollWrite(b);break;case 8198:this.nes.ppu.writeVRAMAddress(b);break;case 8199:this.nes.ppu.vramWrite(b);break;case 16404:this.nes.ppu.sramDMA(b);break;case 16405:this.nes.papu.writeReg(a,b);break;case 16406:if(b===0&&this.joypadLastWrite===1)this.joy2StrobeState=this.joy1StrobeState=0;this.joypadLastWrite=b;break;case 16407:this.nes.papu.writeReg(a,b);break;default:a>=16384&&a<=
16407&&this.nes.papu.writeReg(a,b)}},joy1Read:function(){var a;switch(this.joy1StrobeState){case 0:case 1:case 2:case 3:case 4:case 5:case 6:case 7:a=this.nes.keyboard.state1[this.joy1StrobeState];break;case 8:case 9:case 10:case 11:case 12:case 13:case 14:case 15:case 16:case 17:case 18:a=0;break;case 19:a=1;break;default:a=0}++this.joy1StrobeState;if(this.joy1StrobeState==24)this.joy1StrobeState=0;return a},joy2Read:function(){var a;switch(this.joy2StrobeState){case 0:case 1:case 2:case 3:case 4:case 5:case 6:case 7:a=
this.nes.keyboard.state2[this.joy2StrobeState];break;case 8:case 9:case 10:case 11:case 12:case 13:case 14:case 15:case 16:case 17:case 18:a=0;break;case 19:a=1;break;default:a=0}++this.joy2StrobeState;if(this.joy2StrobeState==24)this.joy2StrobeState=0;return a},loadROM:function(){!this.nes.rom.valid||this.nes.rom.romCount<1?alert("NoMapper: Invalid ROM! Unable to load."):(this.loadPRGROM(),this.loadCHRROM(),this.loadBatteryRam(),this.nes.cpu.requestIrq(this.nes.cpu.IRQ_RESET))},loadPRGROM:function(){this.nes.rom.romCount>
1?(this.loadRomBank(0,32768),this.loadRomBank(1,49152)):(this.loadRomBank(0,32768),this.loadRomBank(0,49152))},loadCHRROM:function(){this.nes.rom.vromCount>0&&(this.nes.rom.vromCount==1?(this.loadVromBank(0,0),this.loadVromBank(0,4096)):(this.loadVromBank(0,0),this.loadVromBank(1,4096)))},loadBatteryRam:function(){if(this.nes.rom.batteryRam){var a=this.nes.rom.batteryRam;a!==null&&a.length==8192&&JSNES.Utils.copyArrayElements(a,0,this.nes.cpu.mem,24576,8192)}},loadRomBank:function(a,b){a%=this.nes.rom.romCount;
JSNES.Utils.copyArrayElements(this.nes.rom.rom[a],0,this.nes.cpu.mem,b,16384)},loadVromBank:function(a,b){this.nes.rom.vromCount!==0&&(this.nes.ppu.triggerRendering(),JSNES.Utils.copyArrayElements(this.nes.rom.vrom[a%this.nes.rom.vromCount],0,this.nes.ppu.vramMem,b,4096),JSNES.Utils.copyArrayElements(this.nes.rom.vromTile[a%this.nes.rom.vromCount],0,this.nes.ppu.ptTile,b>>4,256))},load32kRomBank:function(a,b){this.loadRomBank(a*2%this.nes.rom.romCount,b);this.loadRomBank((a*2+1)%this.nes.rom.romCount,
b+16384)},load8kVromBank:function(a,b){this.nes.rom.vromCount!==0&&(this.nes.ppu.triggerRendering(),this.loadVromBank(a%this.nes.rom.vromCount,b),this.loadVromBank((a+1)%this.nes.rom.vromCount,b+4096))},load1kVromBank:function(a,b){if(this.nes.rom.vromCount!==0){this.nes.ppu.triggerRendering();var d=Math.floor(a/4)%this.nes.rom.vromCount;JSNES.Utils.copyArrayElements(this.nes.rom.vrom[d],0,this.nes.ppu.vramMem,a%4*1024,1024);for(var d=this.nes.rom.vromTile[d],e=b>>4,f=0;f<64;++f)this.nes.ppu.ptTile[e+
f]=d[(a%4<<6)+f]}},load2kVromBank:function(a,b){if(this.nes.rom.vromCount!==0){this.nes.ppu.triggerRendering();var d=Math.floor(a/2)%this.nes.rom.vromCount;JSNES.Utils.copyArrayElements(this.nes.rom.vrom[d],a%2*2048,this.nes.ppu.vramMem,b,2048);for(var d=this.nes.rom.vromTile[d],e=b>>4,f=0;f<128;++f)this.nes.ppu.ptTile[e+f]=d[(a%2<<7)+f]}},load8kRomBank:function(a,b){JSNES.Utils.copyArrayElements(this.nes.rom.rom[Math.floor(a/2)%this.nes.rom.romCount],a%2*8192,this.nes.cpu.mem,b,8192)},clockIrqCounter:function(){},
latchAccess:function(){},toJSON:function(){return{joy1StrobeState:this.joy1StrobeState,joy2StrobeState:this.joy2StrobeState,joypadLastWrite:this.joypadLastWrite}},fromJSON:function(a){this.joy1StrobeState=a.joy1StrobeState;this.joy2StrobeState=a.joy2StrobeState;this.joypadLastWrite=a.joypadLastWrite}};JSNES.Mappers[1]=function(a){this.nes=a};JSNES.Mappers[1].prototype=new JSNES.Mappers[0];
JSNES.Mappers[1].prototype.reset=function(){JSNES.Mappers[0].prototype.reset.apply(this);this.oneScreenMirroring=this.mirroring=this.regBufferCounter=this.regBuffer=0;this.prgSwitchingSize=this.prgSwitchingArea=1;this.romBankSelect=this.romSelectionReg1=this.romSelectionReg0=this.vromSwitchingSize=0};
JSNES.Mappers[1].prototype.write=function(a,b){if(a<32768)JSNES.Mappers[0].prototype.write.apply(this,arguments);else if((b&128)!==0){if(this.regBuffer=this.regBufferCounter=0,this.getRegNumber(a)===0)this.prgSwitchingSize=this.prgSwitchingArea=1}else if(this.regBuffer=this.regBuffer&255-(1<<this.regBufferCounter)|(b&1)<<this.regBufferCounter,++this.regBufferCounter,this.regBufferCounter==5)this.setReg(this.getRegNumber(a),this.regBuffer),this.regBufferCounter=this.regBuffer=0};
JSNES.Mappers[1].prototype.setReg=function(a,b){var d;switch(a){case 0:d=b&3;if(d!==this.mirroring)this.mirroring=d,(this.mirroring&2)===0?this.nes.ppu.setMirroring(this.nes.rom.SINGLESCREEN_MIRRORING):(this.mirroring&1)!==0?this.nes.ppu.setMirroring(this.nes.rom.HORIZONTAL_MIRRORING):this.nes.ppu.setMirroring(this.nes.rom.VERTICAL_MIRRORING);this.prgSwitchingArea=b>>2&1;this.prgSwitchingSize=b>>3&1;this.vromSwitchingSize=b>>4&1;break;case 1:this.romSelectionReg0=b>>4&1;this.nes.rom.vromCount>0&&
(this.vromSwitchingSize===0?this.romSelectionReg0===0?this.load8kVromBank(b&15,0):this.load8kVromBank(Math.floor(this.nes.rom.vromCount/2)+(b&15),0):this.romSelectionReg0===0?this.loadVromBank(b&15,0):this.loadVromBank(Math.floor(this.nes.rom.vromCount/2)+(b&15),0));break;case 2:this.romSelectionReg1=b>>4&1;this.nes.rom.vromCount>0&&this.vromSwitchingSize===1&&(this.romSelectionReg1===0?this.loadVromBank(b&15,4096):this.loadVromBank(Math.floor(this.nes.rom.vromCount/2)+(b&15),4096));break;default:d=
0,this.nes.rom.romCount>=32?this.vromSwitchingSize===0?this.romSelectionReg0===1&&(d=16):d=(this.romSelectionReg0|this.romSelectionReg1<<1)<<3:this.nes.rom.romCount>=16&&this.romSelectionReg0===1&&(d=8),this.prgSwitchingSize===0?this.load32kRomBank(d+(b&15),32768):(d=d*2+(b&15),this.prgSwitchingArea===0?this.loadRomBank(d,49152):this.loadRomBank(d,32768))}};JSNES.Mappers[1].prototype.getRegNumber=function(a){return a>=32768&&a<=40959?0:a>=40960&&a<=49151?1:a>=49152&&a<=57343?2:3};
JSNES.Mappers[1].prototype.loadROM=function(){this.nes.rom.valid?(this.loadRomBank(0,32768),this.loadRomBank(this.nes.rom.romCount-1,49152),this.loadCHRROM(),this.loadBatteryRam(),this.nes.cpu.requestIrq(this.nes.cpu.IRQ_RESET)):alert("MMC1: Invalid ROM! Unable to load.")};JSNES.Mappers[1].prototype.switchLowHighPrgRom=function(){};JSNES.Mappers[1].prototype.switch16to32=function(){};JSNES.Mappers[1].prototype.switch32to16=function(){};
JSNES.Mappers[1].prototype.toJSON=function(){var a=JSNES.Mappers[0].prototype.toJSON.apply(this);a.mirroring=this.mirroring;a.oneScreenMirroring=this.oneScreenMirroring;a.prgSwitchingArea=this.prgSwitchingArea;a.prgSwitchingSize=this.prgSwitchingSize;a.vromSwitchingSize=this.vromSwitchingSize;a.romSelectionReg0=this.romSelectionReg0;a.romSelectionReg1=this.romSelectionReg1;a.romBankSelect=this.romBankSelect;a.regBuffer=this.regBuffer;a.regBufferCounter=this.regBufferCounter;return a};
JSNES.Mappers[1].prototype.fromJSON=function(a){JSNES.Mappers[0].prototype.fromJSON.apply(this,a);this.mirroring=a.mirroring;this.oneScreenMirroring=a.oneScreenMirroring;this.prgSwitchingArea=a.prgSwitchingArea;this.prgSwitchingSize=a.prgSwitchingSize;this.vromSwitchingSize=a.vromSwitchingSize;this.romSelectionReg0=a.romSelectionReg0;this.romSelectionReg1=a.romSelectionReg1;this.romBankSelect=a.romBankSelect;this.regBuffer=a.regBuffer;this.regBufferCounter=a.regBufferCounter};
JSNES.Mappers[2]=function(a){this.nes=a};JSNES.Mappers[2].prototype=new JSNES.Mappers[0];JSNES.Mappers[2].prototype.write=function(a,b){a<32768?JSNES.Mappers[0].prototype.write.apply(this,arguments):this.loadRomBank(b,32768)};JSNES.Mappers[2].prototype.loadROM=function(){this.nes.rom.valid?(this.loadRomBank(0,32768),this.loadRomBank(this.nes.rom.romCount-1,49152),this.loadCHRROM(),this.nes.cpu.requestIrq(this.nes.cpu.IRQ_RESET)):alert("UNROM: Invalid ROM! Unable to load.")};
JSNES.Mappers[4]=function(a){this.nes=a;this.CMD_SEL_2_1K_VROM_0000=0;this.CMD_SEL_2_1K_VROM_0800=1;this.CMD_SEL_1K_VROM_1000=2;this.CMD_SEL_1K_VROM_1400=3;this.CMD_SEL_1K_VROM_1800=4;this.CMD_SEL_1K_VROM_1C00=5;this.CMD_SEL_ROM_PAGE1=6;this.CMD_SEL_ROM_PAGE2=7;this.irqEnable=this.irqLatchValue=this.irqCounter=this.pageNumber=this.chrAddressSelect=this.prgAddressSelect=this.command=null;this.prgAddressChanged=!1};JSNES.Mappers[4].prototype=new JSNES.Mappers[0];
JSNES.Mappers[4].prototype.write=function(a,b){if(a<32768)JSNES.Mappers[0].prototype.write.apply(this,arguments);else switch(a){case 32768:this.command=b&7;var d=b>>6&1;if(d!=this.prgAddressSelect)this.prgAddressChanged=!0;this.prgAddressSelect=d;this.chrAddressSelect=b>>7&1;break;case 32769:this.executeCommand(this.command,b);break;case 40960:(b&1)!==0?this.nes.ppu.setMirroring(this.nes.rom.HORIZONTAL_MIRRORING):this.nes.ppu.setMirroring(this.nes.rom.VERTICAL_MIRRORING);break;case 49152:this.irqCounter=
b;break;case 49153:this.irqLatchValue=b;break;case 57344:this.irqEnable=0;break;case 57345:this.irqEnable=1}};
JSNES.Mappers[4].prototype.executeCommand=function(a,b){switch(a){case this.CMD_SEL_2_1K_VROM_0000:this.chrAddressSelect===0?(this.load1kVromBank(b,0),this.load1kVromBank(b+1,1024)):(this.load1kVromBank(b,4096),this.load1kVromBank(b+1,5120));break;case this.CMD_SEL_2_1K_VROM_0800:this.chrAddressSelect===0?(this.load1kVromBank(b,2048),this.load1kVromBank(b+1,3072)):(this.load1kVromBank(b,6144),this.load1kVromBank(b+1,7168));break;case this.CMD_SEL_1K_VROM_1000:this.chrAddressSelect===0?this.load1kVromBank(b,
4096):this.load1kVromBank(b,0);break;case this.CMD_SEL_1K_VROM_1400:this.chrAddressSelect===0?this.load1kVromBank(b,5120):this.load1kVromBank(b,1024);break;case this.CMD_SEL_1K_VROM_1800:this.chrAddressSelect===0?this.load1kVromBank(b,6144):this.load1kVromBank(b,2048);break;case this.CMD_SEL_1K_VROM_1C00:this.chrAddressSelect===0?this.load1kVromBank(b,7168):this.load1kVromBank(b,3072);break;case this.CMD_SEL_ROM_PAGE1:if(this.prgAddressChanged)this.prgAddressSelect===0?this.load8kRomBank((this.nes.rom.romCount-
1)*2,49152):this.load8kRomBank((this.nes.rom.romCount-1)*2,32768),this.prgAddressChanged=!1;this.prgAddressSelect===0?this.load8kRomBank(b,32768):this.load8kRomBank(b,49152);break;case this.CMD_SEL_ROM_PAGE2:if(this.load8kRomBank(b,40960),this.prgAddressChanged)this.prgAddressSelect===0?this.load8kRomBank((this.nes.rom.romCount-1)*2,49152):this.load8kRomBank((this.nes.rom.romCount-1)*2,32768),this.prgAddressChanged=!1}};
JSNES.Mappers[4].prototype.loadROM=function(){this.nes.rom.valid?(this.load8kRomBank((this.nes.rom.romCount-1)*2,49152),this.load8kRomBank((this.nes.rom.romCount-1)*2+1,57344),this.load8kRomBank(0,32768),this.load8kRomBank(1,40960),this.loadCHRROM(),this.loadBatteryRam(),this.nes.cpu.requestIrq(this.nes.cpu.IRQ_RESET)):alert("MMC3: Invalid ROM! Unable to load.")};
JSNES.Mappers[4].prototype.toJSON=function(){var a=JSNES.Mappers[0].prototype.toJSON.apply(this);a.command=this.command;a.prgAddressSelect=this.prgAddressSelect;a.chrAddressSelect=this.chrAddressSelect;a.pageNumber=this.pageNumber;a.irqCounter=this.irqCounter;a.irqLatchValue=this.irqLatchValue;a.irqEnable=this.irqEnable;a.prgAddressChanged=this.prgAddressChanged;return a};
JSNES.Mappers[4].prototype.fromJSON=function(a){JSNES.Mappers[0].prototype.fromJSON.apply(this,a);this.command=a.command;this.prgAddressSelect=a.prgAddressSelect;this.chrAddressSelect=a.chrAddressSelect;this.pageNumber=a.pageNumber;this.irqCounter=a.irqCounter;this.irqLatchValue=a.irqLatchValue;this.irqEnable=a.irqEnable;this.prgAddressChanged=a.prgAddressChanged};JSNES.PAPU=function(a){this.nes=a;this.square1=new JSNES.PAPU.ChannelSquare(this,!0);this.square2=new JSNES.PAPU.ChannelSquare(this,!1);this.triangle=new JSNES.PAPU.ChannelTriangle(this);this.noise=new JSNES.PAPU.ChannelNoise(this);this.dmc=new JSNES.PAPU.ChannelDM(this);this.frameIrqCounter=null;this.frameIrqCounterMax=4;this.initCounter=2048;this.channelEnableValue=null;this.bufferSize=8192;this.bufferIndex=0;this.sampleRate=44100;this.tnd_table=this.square_table=this.noiseWavelengthLookup=this.dmcFreqLookup=
this.lengthLookup=null;this.sampleBuffer=Array(this.bufferSize*2);this.frameIrqEnabled=!1;this.frameClockNow=this.frameIrqActive=null;this.initingHardware=this.recordOutput=this.startedPlaying=!1;this.sampleCount=this.sampleTimerMax=this.frameTime=this.sampleTimer=this.countSequence=this.derivedFrameCounter=this.masterFrameCounter=null;this.triValue=0;this.accCount=this.smpDmc=this.smpTriangle=this.smpSquare2=this.smpSquare1=null;this.dcValue=this.dacRange=this.smpAccumR=this.smpAccumL=this.prevSampleR=
this.prevSampleL=0;this.masterVolume=256;this.minSample=this.maxSample=this.extraCycles=this.stereoPosRDMC=this.stereoPosRNoise=this.stereoPosRTriangle=this.stereoPosRSquare2=this.stereoPosRSquare1=this.stereoPosLDMC=this.stereoPosLNoise=this.stereoPosLTriangle=this.stereoPosLSquare2=this.stereoPosLSquare1=null;this.panning=[80,170,100,150,128];this.setPanning(this.panning);this.initLengthLookup();this.initDmcFrequencyLookup();this.initNoiseWavelengthLookup();this.initDACtables();for(a=0;a<20;++a)a===
16?this.writeReg(16400,16):this.writeReg(16384+a,0);this.reset()};
JSNES.PAPU.prototype={reset:function(){this.sampleRate=this.nes.opts.sampleRate;this.sampleTimerMax=Math.floor(1024*this.nes.opts.CPU_FREQ_NTSC*this.nes.opts.preferredFrameRate/(this.sampleRate*60));this.frameTime=Math.floor(14915*this.nes.opts.preferredFrameRate/60);this.bufferIndex=this.sampleTimer=0;this.updateChannelEnable(0);this.sampleCount=this.countSequence=this.derivedFrameCounter=this.masterFrameCounter=0;this.initCounter=2048;this.initingHardware=this.frameIrqEnabled=!1;this.resetCounter();
this.square1.reset();this.square2.reset();this.triangle.reset();this.noise.reset();this.dmc.reset();this.smpDmc=this.smpTriangle=this.smpSquare2=this.smpSquare1=this.accCount=this.bufferIndex=0;this.frameIrqEnabled=!1;this.frameIrqCounterMax=4;this.channelEnableValue=255;this.startedPlaying=!1;this.smpAccumR=this.smpAccumL=this.prevSampleR=this.prevSampleL=0;this.maxSample=-5E5;this.minSample=5E5},readReg:function(){var a=0;a|=this.square1.getLengthStatus();a|=this.square2.getLengthStatus()<<1;a|=
this.triangle.getLengthStatus()<<2;a|=this.noise.getLengthStatus()<<3;a|=this.dmc.getLengthStatus()<<4;a|=(this.frameIrqActive&&this.frameIrqEnabled?1:0)<<6;a|=this.dmc.getIrqStatus()<<7;this.frameIrqActive=!1;this.dmc.irqGenerated=!1;return a&65535},writeReg:function(a,b){if(a>=16384&&a<16388)this.square1.writeReg(a,b);else if(a>=16388&&a<16392)this.square2.writeReg(a,b);else if(a>=16392&&a<16396)this.triangle.writeReg(a,b);else if(a>=16396&&a<=16399)this.noise.writeReg(a,b);else if(a===16400)this.dmc.writeReg(a,
b);else if(a===16401)this.dmc.writeReg(a,b);else if(a===16402)this.dmc.writeReg(a,b);else if(a===16403)this.dmc.writeReg(a,b);else if(a===16405){this.updateChannelEnable(b);if(b!==0&&this.initCounter>0)this.initingHardware=!0;this.dmc.writeReg(a,b)}else if(a===16407)this.countSequence=b>>7&1,this.masterFrameCounter=0,this.frameIrqActive=!1,this.frameIrqEnabled=(b>>6&1)===0?!0:!1,this.countSequence===0?this.derivedFrameCounter=this.frameIrqCounterMax=4:(this.frameIrqCounterMax=5,this.derivedFrameCounter=
0,this.frameCounterTick())},resetCounter:function(){this.derivedFrameCounter=this.countSequence===0?4:0},updateChannelEnable:function(a){this.channelEnableValue=a&65535;this.square1.setEnabled((a&1)!==0);this.square2.setEnabled((a&2)!==0);this.triangle.setEnabled((a&4)!==0);this.noise.setEnabled((a&8)!==0);this.dmc.setEnabled((a&16)!==0)},clockFrameCounter:function(a){if(this.initCounter>0&&this.initingHardware){if(this.initCounter-=a,this.initCounter<=0)this.initingHardware=!1}else{a+=this.extraCycles;
var b=this.sampleTimerMax-this.sampleTimer;a<<10>b?(this.extraCycles=(a<<10)-b>>10,a-=this.extraCycles):this.extraCycles=0;var d=this.dmc,e=this.triangle,f=this.square1,c=this.square2,b=this.noise;if(d.isEnabled)for(d.shiftCounter-=a<<3;d.shiftCounter<=0&&d.dmaFrequency>0;)d.shiftCounter+=d.dmaFrequency,d.clockDmc();if(e.progTimerMax>0)for(e.progTimerCount-=a;e.progTimerCount<=0;)if(e.progTimerCount+=e.progTimerMax+1,e.linearCounter>0&&e.lengthCounter>0&&(++e.triangleCounter,e.triangleCounter&=31,
e.isEnabled))e.sampleValue=e.triangleCounter>=16?e.triangleCounter&15:15-(e.triangleCounter&15),e.sampleValue<<=4;f.progTimerCount-=a;f.progTimerCount<=0&&(f.progTimerCount+=f.progTimerMax+1<<1,++f.squareCounter,f.squareCounter&=7,f.updateSampleValue());c.progTimerCount-=a;c.progTimerCount<=0&&(c.progTimerCount+=c.progTimerMax+1<<1,++c.squareCounter,c.squareCounter&=7,c.updateSampleValue());d=a;if(b.progTimerCount-d>0)b.progTimerCount-=d,b.accCount+=d,b.accValue+=d*b.sampleValue;else for(;--d>0;){if(--b.progTimerCount<=
0&&b.progTimerMax>0)b.shiftReg<<=1,b.tmp=(b.shiftReg<<(b.randomMode===0?1:6)^b.shiftReg)&32768,b.tmp!==0?(b.shiftReg|=1,b.randomBit=0,b.sampleValue=0):(b.randomBit=1,b.sampleValue=b.isEnabled&&b.lengthCounter>0?b.masterVolume:0),b.progTimerCount+=b.progTimerMax;b.accValue+=b.sampleValue;++b.accCount}this.frameIrqEnabled&&this.frameIrqActive&&this.nes.cpu.requestIrq(this.nes.cpu.IRQ_NORMAL);this.masterFrameCounter+=a<<1;this.masterFrameCounter>=this.frameTime&&(this.masterFrameCounter-=this.frameTime,
this.frameCounterTick());this.accSample(a);this.sampleTimer+=a<<10;this.sampleTimer>=this.sampleTimerMax&&(this.sample(),this.sampleTimer-=this.sampleTimerMax)}},accSample:function(a){if(this.triangle.sampleCondition){this.triValue=Math.floor((this.triangle.progTimerCount<<4)/(this.triangle.progTimerMax+1));if(this.triValue>16)this.triValue=16;if(this.triangle.triangleCounter>=16)this.triValue=16-this.triValue;this.triValue+=this.triangle.sampleValue}a===2?(this.smpTriangle+=this.triValue<<1,this.smpDmc+=
this.dmc.sample<<1,this.smpSquare1+=this.square1.sampleValue<<1,this.smpSquare2+=this.square2.sampleValue<<1,this.accCount+=2):a===4?(this.smpTriangle+=this.triValue<<2,this.smpDmc+=this.dmc.sample<<2,this.smpSquare1+=this.square1.sampleValue<<2,this.smpSquare2+=this.square2.sampleValue<<2,this.accCount+=4):(this.smpTriangle+=a*this.triValue,this.smpDmc+=a*this.dmc.sample,this.smpSquare1+=a*this.square1.sampleValue,this.smpSquare2+=a*this.square2.sampleValue,this.accCount+=a)},frameCounterTick:function(){++this.derivedFrameCounter;
if(this.derivedFrameCounter>=this.frameIrqCounterMax)this.derivedFrameCounter=0;if(this.derivedFrameCounter===1||this.derivedFrameCounter===3)this.triangle.clockLengthCounter(),this.square1.clockLengthCounter(),this.square2.clockLengthCounter(),this.noise.clockLengthCounter(),this.square1.clockSweep(),this.square2.clockSweep();this.derivedFrameCounter>=0&&this.derivedFrameCounter<4&&(this.square1.clockEnvDecay(),this.square2.clockEnvDecay(),this.noise.clockEnvDecay(),this.triangle.clockLinearCounter());
if(this.derivedFrameCounter===3&&this.countSequence===0)this.frameIrqActive=!0},sample:function(){var a,b;this.accCount>0?(this.smpSquare1<<=4,this.smpSquare1=Math.floor(this.smpSquare1/this.accCount),this.smpSquare2<<=4,this.smpSquare2=Math.floor(this.smpSquare2/this.accCount),this.smpTriangle=Math.floor(this.smpTriangle/this.accCount),this.smpDmc<<=4,this.smpDmc=Math.floor(this.smpDmc/this.accCount),this.accCount=0):(this.smpSquare1=this.square1.sampleValue<<4,this.smpSquare2=this.square2.sampleValue<<
4,this.smpTriangle=this.triangle.sampleValue,this.smpDmc=this.dmc.sample<<4);var d=Math.floor((this.noise.accValue<<4)/this.noise.accCount);this.noise.accValue=d>>4;this.noise.accCount=1;a=this.smpSquare1*this.stereoPosLSquare1+this.smpSquare2*this.stereoPosLSquare2>>8;b=3*this.smpTriangle*this.stereoPosLTriangle+(d<<1)*this.stereoPosLNoise+this.smpDmc*this.stereoPosLDMC>>8;a>=this.square_table.length&&(a=this.square_table.length-1);b>=this.tnd_table.length&&(b=this.tnd_table.length-1);var e=this.square_table[a]+
this.tnd_table[b]-this.dcValue;a=this.smpSquare1*this.stereoPosRSquare1+this.smpSquare2*this.stereoPosRSquare2>>8;b=3*this.smpTriangle*this.stereoPosRTriangle+(d<<1)*this.stereoPosRNoise+this.smpDmc*this.stereoPosRDMC>>8;a>=this.square_table.length&&(a=this.square_table.length-1);b>=this.tnd_table.length&&(b=this.tnd_table.length-1);a=this.square_table[a]+this.tnd_table[b]-this.dcValue;e-=this.prevSampleL;this.prevSampleL+=e;this.smpAccumL+=e-(this.smpAccumL>>10);e=this.smpAccumL;a-=this.prevSampleR;
this.prevSampleR+=a;this.smpAccumR+=a-(this.smpAccumR>>10);a=this.smpAccumR;if(e>this.maxSample)this.maxSample=e;if(e<this.minSample)this.minSample=e;this.sampleBuffer[++this.bufferIndex]=e;this.sampleBuffer[++this.bufferIndex]=a;if(this.bufferIndex===this.sampleBuffer.length)this.nes.ui.writeAudio(this.sampleBuffer),this.sampleBuffer=Array(this.bufferSize*2),this.bufferIndex=0;this.smpDmc=this.smpTriangle=this.smpSquare2=this.smpSquare1=0},getLengthMax:function(a){return this.lengthLookup[a>>3]},
getDmcFrequency:function(a){if(a>=0&&a<16)return this.dmcFreqLookup[a];return 0},getNoiseWaveLength:function(a){if(a>=0&&a<16)return this.noiseWavelengthLookup[a];return 0},setPanning:function(a){for(var b=0;b<5;++b)this.panning[b]=a[b];this.updateStereoPos()},setMasterVolume:function(a){a<0&&(a=0);a>256&&(a=256);this.masterVolume=a;this.updateStereoPos()},updateStereoPos:function(){this.stereoPosLSquare1=this.panning[0]*this.masterVolume>>8;this.stereoPosLSquare2=this.panning[1]*this.masterVolume>>
8;this.stereoPosLTriangle=this.panning[2]*this.masterVolume>>8;this.stereoPosLNoise=this.panning[3]*this.masterVolume>>8;this.stereoPosLDMC=this.panning[4]*this.masterVolume>>8;this.stereoPosRSquare1=this.masterVolume-this.stereoPosLSquare1;this.stereoPosRSquare2=this.masterVolume-this.stereoPosLSquare2;this.stereoPosRTriangle=this.masterVolume-this.stereoPosLTriangle;this.stereoPosRNoise=this.masterVolume-this.stereoPosLNoise;this.stereoPosRDMC=this.masterVolume-this.stereoPosLDMC},initLengthLookup:function(){this.lengthLookup=
[10,254,20,2,40,4,80,6,160,8,60,10,14,12,26,14,12,16,24,18,48,20,96,22,192,24,72,26,16,28,32,30]},initDmcFrequencyLookup:function(){this.dmcFreqLookup=Array(16);this.dmcFreqLookup[0]=3424;this.dmcFreqLookup[1]=3040;this.dmcFreqLookup[2]=2720;this.dmcFreqLookup[3]=2560;this.dmcFreqLookup[4]=2288;this.dmcFreqLookup[5]=2032;this.dmcFreqLookup[6]=1808;this.dmcFreqLookup[7]=1712;this.dmcFreqLookup[8]=1520;this.dmcFreqLookup[9]=1280;this.dmcFreqLookup[10]=1136;this.dmcFreqLookup[11]=1024;this.dmcFreqLookup[12]=
848;this.dmcFreqLookup[13]=672;this.dmcFreqLookup[14]=576;this.dmcFreqLookup[15]=432},initNoiseWavelengthLookup:function(){this.noiseWavelengthLookup=Array(16);this.noiseWavelengthLookup[0]=4;this.noiseWavelengthLookup[1]=8;this.noiseWavelengthLookup[2]=16;this.noiseWavelengthLookup[3]=32;this.noiseWavelengthLookup[4]=64;this.noiseWavelengthLookup[5]=96;this.noiseWavelengthLookup[6]=128;this.noiseWavelengthLookup[7]=160;this.noiseWavelengthLookup[8]=202;this.noiseWavelengthLookup[9]=254;this.noiseWavelengthLookup[10]=
380;this.noiseWavelengthLookup[11]=508;this.noiseWavelengthLookup[12]=762;this.noiseWavelengthLookup[13]=1016;this.noiseWavelengthLookup[14]=2034;this.noiseWavelengthLookup[15]=4068},initDACtables:function(){var a,b,d=0,e=0;this.square_table=Array(512);this.tnd_table=Array(3264);for(b=0;b<512;++b)a=95.52/(8128/(b/16)+100),a*=0.98411,a*=5E4,a=Math.floor(a),this.square_table[b]=a,a>d&&(d=a);for(b=0;b<3264;++b)a=163.67/(24329/(b/16)+100),a*=0.98411,a*=5E4,a=Math.floor(a),this.tnd_table[b]=a,a>e&&(e=
a);this.dacRange=d+e;this.dcValue=this.dacRange/2}};JSNES.PAPU.ChannelDM=function(a){this.papu=a;this.MODE_NORMAL=0;this.MODE_LOOP=1;this.MODE_IRQ=2;this.hasSample=this.isEnabled=null;this.irqGenerated=!1;this.data=this.dacLsb=this.sample=this.reg4013=this.reg4012=this.shiftCounter=this.playLengthCounter=this.playLength=this.playAddress=this.playStartAddress=this.deltaCounter=this.dmaCounter=this.dmaFrequency=this.playMode=null;this.reset()};
JSNES.PAPU.ChannelDM.prototype={clockDmc:function(){if(this.hasSample)(this.data&1)===0?this.deltaCounter>0&&--this.deltaCounter:this.deltaCounter<63&&++this.deltaCounter,this.sample=this.isEnabled?(this.deltaCounter<<1)+this.dacLsb:0,this.data>>=1;--this.dmaCounter;if(this.dmaCounter<=0)this.hasSample=!1,this.endOfSample(),this.dmaCounter=8;this.irqGenerated&&this.papu.nes.cpu.requestIrq(this.papu.nes.cpu.IRQ_NORMAL)},endOfSample:function(){if(this.playLengthCounter===0&&this.playMode===this.MODE_LOOP)this.playAddress=
this.playStartAddress,this.playLengthCounter=this.playLength;if(this.playLengthCounter>0&&(this.nextSample(),this.playLengthCounter===0&&this.playMode===this.MODE_IRQ))this.irqGenerated=!0},nextSample:function(){this.data=this.papu.nes.mmap.load(this.playAddress);this.papu.nes.cpu.haltCycles(4);--this.playLengthCounter;++this.playAddress;if(this.playAddress>65535)this.playAddress=32768;this.hasSample=!0},writeReg:function(a,b){if(a===16400){if(b>>6===0)this.playMode=this.MODE_NORMAL;else if((b>>6&
1)===1)this.playMode=this.MODE_LOOP;else if(b>>6===2)this.playMode=this.MODE_IRQ;if((b&128)===0)this.irqGenerated=!1;this.dmaFrequency=this.papu.getDmcFrequency(b&15)}else if(a===16401)this.deltaCounter=b>>1&63,this.dacLsb=b&1,this.sample=(this.deltaCounter<<1)+this.dacLsb;else if(a===16402)this.playAddress=this.playStartAddress=b<<6|49152,this.reg4012=b;else if(a===16403)this.playLengthCounter=this.playLength=(b<<4)+1,this.reg4013=b;else if(a===16405)(b>>4&1)===0?this.playLengthCounter=0:(this.playAddress=
this.playStartAddress,this.playLengthCounter=this.playLength),this.irqGenerated=!1},setEnabled:function(a){if(!this.isEnabled&&a)this.playLengthCounter=this.playLength;this.isEnabled=a},getLengthStatus:function(){return this.playLengthCounter===0||!this.isEnabled?0:1},getIrqStatus:function(){return this.irqGenerated?1:0},reset:function(){this.irqGenerated=this.isEnabled=!1;this.playMode=this.MODE_NORMAL;this.data=this.reg4013=this.reg4012=this.shiftCounter=this.dacLsb=this.sample=this.playLengthCounter=
this.playLength=this.playAddress=this.playStartAddress=this.deltaCounter=this.dmaCounter=this.dmaFrequency=0}};
JSNES.PAPU.ChannelNoise=function(a){this.papu=a;this.masterVolume=this.envVolume=this.envDecayCounter=this.envDecayRate=this.progTimerMax=this.progTimerCount=this.lengthCounter=this.shiftNow=this.envReset=this.lengthCounterEnable=this.envDecayLoopEnable=this.envDecayDisable=this.isEnabled=null;this.shiftReg=16384;this.sampleValue=this.randomMode=this.randomBit=null;this.accValue=0;this.accCount=1;this.tmp=null;this.reset()};
JSNES.PAPU.ChannelNoise.prototype={reset:function(){this.progTimerMax=this.progTimerCount=0;this.isEnabled=!1;this.lengthCounter=0;this.shiftNow=this.envDecayLoopEnable=this.envDecayDisable=this.lengthCounterEnable=!1;this.masterVolume=this.envVolume=this.envDecayCounter=this.envDecayRate=0;this.shiftReg=1;this.tmp=this.sampleValue=this.randomMode=this.randomBit=0},clockLengthCounter:function(){this.lengthCounterEnable&&this.lengthCounter>0&&(--this.lengthCounter,this.lengthCounter===0&&this.updateSampleValue())},
clockEnvDecay:function(){if(this.envReset)this.envReset=!1,this.envDecayCounter=this.envDecayRate+1,this.envVolume=15;else if(--this.envDecayCounter<=0)this.envDecayCounter=this.envDecayRate+1,this.envVolume>0?--this.envVolume:this.envVolume=this.envDecayLoopEnable?15:0;this.masterVolume=this.envDecayDisable?this.envDecayRate:this.envVolume;this.updateSampleValue()},updateSampleValue:function(){if(this.isEnabled&&this.lengthCounter>0)this.sampleValue=this.randomBit*this.masterVolume},writeReg:function(a,
b){if(a===16396)this.envDecayDisable=(b&16)!==0,this.envDecayRate=b&15,this.envDecayLoopEnable=(b&32)!==0,this.lengthCounterEnable=(b&32)===0,this.masterVolume=this.envDecayDisable?this.envDecayRate:this.envVolume;else if(a===16398)this.progTimerMax=this.papu.getNoiseWaveLength(b&15),this.randomMode=b>>7;else if(a===16399)this.lengthCounter=this.papu.getLengthMax(b&248),this.envReset=!0},setEnabled:function(a){this.isEnabled=a;if(!a)this.lengthCounter=0;this.updateSampleValue()},getLengthStatus:function(){return this.lengthCounter===
0||!this.isEnabled?0:1}};
JSNES.PAPU.ChannelSquare=function(a,b){this.papu=a;this.dutyLookup=[0,1,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,1,1,1,1,0,0,0,1,0,0,1,1,1,1,1];this.impLookup=[1,-1,0,0,0,0,0,0,1,0,-1,0,0,0,0,0,1,0,0,0,-1,0,0,0,-1,0,1,0,0,0,0,0];this.sqr1=b;this.vol=this.sampleValue=this.sweepResult=this.dutyMode=this.masterVolume=this.envVolume=this.envDecayCounter=this.envDecayRate=this.sweepShiftAmount=this.sweepMode=this.sweepCounterMax=this.sweepCounter=this.squareCounter=this.lengthCounter=this.progTimerMax=this.progTimerCount=
this.updateSweepPeriod=this.sweepCarry=this.envReset=this.envDecayLoopEnable=this.envDecayDisable=this.sweepActive=this.lengthCounterEnable=this.isEnabled=null;this.reset()};
JSNES.PAPU.ChannelSquare.prototype={reset:function(){this.vol=this.dutyMode=this.masterVolume=this.envVolume=this.envDecayCounter=this.envDecayRate=this.sweepShiftAmount=this.sweepMode=this.sweepCounterMax=this.sweepCounter=this.squareCounter=this.lengthCounter=this.progTimerMax=this.progTimerCount=0;this.envDecayLoopEnable=this.envDecayDisable=this.sweepCarry=this.sweepActive=this.lengthCounterEnable=this.isEnabled=!1},clockLengthCounter:function(){this.lengthCounterEnable&&this.lengthCounter>0&&
(--this.lengthCounter,this.lengthCounter===0&&this.updateSampleValue())},clockEnvDecay:function(){if(this.envReset)this.envReset=!1,this.envDecayCounter=this.envDecayRate+1,this.envVolume=15;else if(--this.envDecayCounter<=0)this.envDecayCounter=this.envDecayRate+1,this.envVolume>0?--this.envVolume:this.envVolume=this.envDecayLoopEnable?15:0;this.masterVolume=this.envDecayDisable?this.envDecayRate:this.envVolume;this.updateSampleValue()},clockSweep:function(){if(--this.sweepCounter<=0&&(this.sweepCounter=
this.sweepCounterMax+1,this.sweepActive&&this.sweepShiftAmount>0&&this.progTimerMax>7))if(this.sweepCarry=!1,this.sweepMode===0){if(this.progTimerMax+=this.progTimerMax>>this.sweepShiftAmount,this.progTimerMax>4095)this.progTimerMax=4095,this.sweepCarry=!0}else this.progTimerMax-=(this.progTimerMax>>this.sweepShiftAmount)-(this.sqr1?1:0);if(this.updateSweepPeriod)this.updateSweepPeriod=!1,this.sweepCounter=this.sweepCounterMax+1},updateSampleValue:function(){this.sampleValue=this.isEnabled&&this.lengthCounter>
0&&this.progTimerMax>7?this.sweepMode===0&&this.progTimerMax+(this.progTimerMax>>this.sweepShiftAmount)>4095?0:this.masterVolume*this.dutyLookup[(this.dutyMode<<3)+this.squareCounter]:0},writeReg:function(a,b){var d=this.sqr1?0:4;if(a===16384+d)this.envDecayDisable=(b&16)!==0,this.envDecayRate=b&15,this.envDecayLoopEnable=(b&32)!==0,this.dutyMode=b>>6&3,this.lengthCounterEnable=(b&32)===0,this.masterVolume=this.envDecayDisable?this.envDecayRate:this.envVolume,this.updateSampleValue();else if(a===
16385+d)this.sweepActive=(b&128)!==0,this.sweepCounterMax=b>>4&7,this.sweepMode=b>>3&1,this.sweepShiftAmount=b&7,this.updateSweepPeriod=!0;else if(a===16386+d)this.progTimerMax&=1792,this.progTimerMax|=b;else if(a===16387+d){this.progTimerMax&=255;this.progTimerMax|=(b&7)<<8;if(this.isEnabled)this.lengthCounter=this.papu.getLengthMax(b&248);this.envReset=!0}},setEnabled:function(a){this.isEnabled=a;if(!a)this.lengthCounter=0;this.updateSampleValue()},getLengthStatus:function(){return this.lengthCounter===
0||!this.isEnabled?0:1}};JSNES.PAPU.ChannelTriangle=function(a){this.papu=a;this.tmp=this.sampleValue=this.lcLoadValue=this.linearCounter=this.lengthCounter=this.triangleCounter=this.progTimerMax=this.progTimerCount=this.lcControl=this.lcHalt=this.lengthCounterEnable=this.sampleCondition=this.isEnabled=null;this.reset()};
JSNES.PAPU.ChannelTriangle.prototype={reset:function(){this.triangleCounter=this.progTimerMax=this.progTimerCount=0;this.sampleCondition=this.isEnabled=!1;this.lengthCounter=0;this.lengthCounterEnable=!1;this.lcLoadValue=this.linearCounter=0;this.lcHalt=!0;this.lcControl=!1;this.tmp=0;this.sampleValue=15},clockLengthCounter:function(){this.lengthCounterEnable&&this.lengthCounter>0&&(--this.lengthCounter,this.lengthCounter===0&&this.updateSampleCondition())},clockLinearCounter:function(){this.lcHalt?
(this.linearCounter=this.lcLoadValue,this.updateSampleCondition()):this.linearCounter>0&&(--this.linearCounter,this.updateSampleCondition());if(!this.lcControl)this.lcHalt=!1},getLengthStatus:function(){return this.lengthCounter===0||!this.isEnabled?0:1},readReg:function(){return 0},writeReg:function(a,b){if(a===16392)this.lcControl=(b&128)!==0,this.lcLoadValue=b&127,this.lengthCounterEnable=!this.lcControl;else if(a===16394)this.progTimerMax&=1792,this.progTimerMax|=b;else if(a===16395)this.progTimerMax&=
255,this.progTimerMax|=(b&7)<<8,this.lengthCounter=this.papu.getLengthMax(b&248),this.lcHalt=!0;this.updateSampleCondition()},clockProgrammableTimer:function(a){if(this.progTimerMax>0)for(this.progTimerCount+=a;this.progTimerMax>0&&this.progTimerCount>=this.progTimerMax;)this.progTimerCount-=this.progTimerMax,this.isEnabled&&this.lengthCounter>0&&this.linearCounter>0&&this.clockTriangleGenerator()},clockTriangleGenerator:function(){++this.triangleCounter;this.triangleCounter&=31},setEnabled:function(a){this.isEnabled=
a;if(!a)this.lengthCounter=0;this.updateSampleCondition()},updateSampleCondition:function(){this.sampleCondition=this.isEnabled&&this.progTimerMax>7&&this.linearCounter>0&&this.lengthCounter>0}};JSNES.PPU=function(a){this.nes=a;this.palTable=this.vramMirrorTable=this.nameTable=this.currentMirroring=this.ntable1=this.ptTile=this.imgPalette=this.sprPalette=this.hitSpr0=this.spr0HitY=this.spr0HitX=this.bgPriority=this.horiFlip=this.vertFlip=this.sprCol=this.sprTile=this.sprY=this.sprX=this.curX=this.lastRenderedScanline=this.scanline=this.scantile=this.validTileData=this.pixrendered=this.bgbuffer=this.prevBuffer=this.buffer=this.attrib=this.curNt=this.regS=this.regFH=this.regHT=this.regVT=this.regH=
this.regV=this.regFV=this.cntHT=this.cntVT=this.cntH=this.cntV=this.cntFV=this.f_dispType=this.f_bgClipping=this.f_spClipping=this.f_bgVisibility=this.f_spVisibility=this.f_color=this.f_nTblAddress=this.f_addrInc=this.f_spPatternTable=this.f_bgPatternTable=this.f_spriteSize=this.f_nmiOnVblank=this.scanlineAlreadyRendered=this.nmiCounter=this.validTileData=this.dummyCycleToggle=this.nmiOk=this.requestEndFrame=this.currentMirroring=this.sramAddress=this.firstWrite=this.vramBufferedReadValue=this.vramTmpAddress=
this.vramAddress=this.spriteMem=this.vramMem=null;this.showSpr0Hit=!1;this.clipToTvSize=!0;this.reset()};
JSNES.PPU.prototype={STATUS_VRAMWRITE:4,STATUS_SLSPRITECOUNT:5,STATUS_SPRITE0HIT:6,STATUS_VBLANK:7,reset:function(){var a;this.vramMem=Array(32768);this.spriteMem=Array(256);for(a=0;a<this.vramMem.length;++a)this.vramMem[a]=0;for(a=0;a<this.spriteMem.length;++a)this.spriteMem[a]=0;this.vramTmpAddress=this.vramAddress=null;this.vramBufferedReadValue=0;this.firstWrite=!0;this.sramAddress=0;this.currentMirroring=-1;this.validTileData=this.dummyCycleToggle=this.nmiOk=this.requestEndFrame=!1;this.nmiCounter=
0;this.scanlineAlreadyRendered=null;this.regS=this.regFH=this.regHT=this.regVT=this.regH=this.regV=this.regFV=this.cntHT=this.cntVT=this.cntH=this.cntV=this.cntFV=this.f_dispType=this.f_bgClipping=this.f_spClipping=this.f_bgVisibility=this.f_spVisibility=this.f_color=this.f_nTblAddress=this.f_addrInc=this.f_spPatternTable=this.f_bgPatternTable=this.f_spriteSize=this.f_nmiOnVblank=0;this.curNt=null;this.attrib=Array(32);this.buffer=Array(61440);this.prevBuffer=Array(61440);this.bgbuffer=Array(61440);
this.pixrendered=Array(61440);this.validTileData=null;this.scantile=Array(32);this.scanline=0;this.lastRenderedScanline=-1;this.curX=0;this.sprX=Array(64);this.sprY=Array(64);this.sprTile=Array(64);this.sprCol=Array(64);this.vertFlip=Array(64);this.horiFlip=Array(64);this.bgPriority=Array(64);this.spr0HitY=this.spr0HitX=0;this.hitSpr0=!1;this.sprPalette=Array(16);this.imgPalette=Array(16);this.ptTile=Array(512);for(a=0;a<512;++a)this.ptTile[a]=new JSNES.PPU.Tile;this.ntable1=Array(4);this.currentMirroring=
-1;this.nameTable=Array(4);for(a=0;a<4;++a)this.nameTable[a]=new JSNES.PPU.NameTable(32,32,"Nt"+a);this.vramMirrorTable=Array(32768);for(a=0;a<32768;++a)this.vramMirrorTable[a]=a;this.palTable=new JSNES.PPU.PaletteTable;this.palTable.loadNTSCPalette();this.updateControlReg1(0);this.updateControlReg2(0)},setMirroring:function(a){if(a!=this.currentMirroring){this.currentMirroring=a;this.triggerRendering();if(this.vramMirrorTable===null)this.vramMirrorTable=Array(32768);for(var b=0;b<32768;++b)this.vramMirrorTable[b]=
b;this.defineMirrorRegion(16160,16128,32);this.defineMirrorRegion(16192,16128,32);this.defineMirrorRegion(16256,16128,32);this.defineMirrorRegion(16320,16128,32);this.defineMirrorRegion(12288,8192,3840);this.defineMirrorRegion(16384,0,16384);a==this.nes.rom.HORIZONTAL_MIRRORING?(this.ntable1[0]=0,this.ntable1[1]=0,this.ntable1[2]=1,this.ntable1[3]=1,this.defineMirrorRegion(9216,8192,1024),this.defineMirrorRegion(11264,10240,1024)):a==this.nes.rom.VERTICAL_MIRRORING?(this.ntable1[0]=0,this.ntable1[1]=
1,this.ntable1[2]=0,this.ntable1[3]=1,this.defineMirrorRegion(10240,8192,1024),this.defineMirrorRegion(11264,9216,1024)):a==this.nes.rom.SINGLESCREEN_MIRRORING?(this.ntable1[0]=0,this.ntable1[1]=0,this.ntable1[2]=0,this.ntable1[3]=0,this.defineMirrorRegion(9216,8192,1024),this.defineMirrorRegion(10240,8192,1024),this.defineMirrorRegion(11264,8192,1024)):a==this.nes.rom.SINGLESCREEN_MIRRORING2?(this.ntable1[0]=1,this.ntable1[1]=1,this.ntable1[2]=1,this.ntable1[3]=1,this.defineMirrorRegion(9216,9216,
1024),this.defineMirrorRegion(10240,9216,1024),this.defineMirrorRegion(11264,9216,1024)):(this.ntable1[0]=0,this.ntable1[1]=1,this.ntable1[2]=2,this.ntable1[3]=3)}},defineMirrorRegion:function(a,b,d){for(var e=0;e<d;++e)this.vramMirrorTable[a+e]=b+e},startVBlank:function(){this.nes.cpu.requestIrq(this.nes.cpu.IRQ_NMI);this.lastRenderedScanline<239&&this.renderFramePartially(this.lastRenderedScanline+1,240-this.lastRenderedScanline);this.endFrame();this.lastRenderedScanline=-1},endScanline:function(){switch(this.scanline){case 19:if(this.dummyCycleToggle)this.curX=
1,this.dummyCycleToggle=!this.dummyCycleToggle;break;case 20:this.setStatusFlag(this.STATUS_VBLANK,!1);this.setStatusFlag(this.STATUS_SPRITE0HIT,!1);this.hitSpr0=!1;this.spr0HitY=this.spr0HitX=-1;if(this.f_bgVisibility==1||this.f_spVisibility==1)this.cntFV=this.regFV,this.cntV=this.regV,this.cntH=this.regH,this.cntVT=this.regVT,this.cntHT=this.regHT,this.f_bgVisibility==1&&this.renderBgScanline(!1,0);this.f_bgVisibility==1&&this.f_spVisibility==1&&this.checkSprite0(0);(this.f_bgVisibility==1||this.f_spVisibility==
1)&&this.nes.mmap.clockIrqCounter();break;case 261:this.setStatusFlag(this.STATUS_VBLANK,!0);this.requestEndFrame=!0;this.nmiCounter=9;this.scanline=-1;break;default:if(this.scanline>=21&&this.scanline<=260){if(this.f_bgVisibility==1){if(!this.scanlineAlreadyRendered)this.cntHT=this.regHT,this.cntH=this.regH,this.renderBgScanline(!0,this.scanline+1-21);this.scanlineAlreadyRendered=!1;if(!this.hitSpr0&&this.f_spVisibility==1&&this.sprX[0]>=-7&&this.sprX[0]<256&&this.sprY[0]+1<=this.scanline-20&&this.sprY[0]+
1+(this.f_spriteSize===0?8:16)>=this.scanline-20&&this.checkSprite0(this.scanline-20))this.hitSpr0=!0}(this.f_bgVisibility==1||this.f_spVisibility==1)&&this.nes.mmap.clockIrqCounter()}}++this.scanline;this.regsToAddress();this.cntsToAddress()},startFrame:function(){var a=0;if(this.f_dispType===0)a=this.imgPalette[0];else switch(this.f_color){case 0:a=0;break;case 1:a=65280;break;case 2:a=16711680;break;case 3:a=0;break;case 4:a=255;break;default:a=0}var b=this.buffer,d;for(d=0;d<61440;++d)b[d]=a;
a=this.pixrendered;for(d=0;d<a.length;++d)a[d]=65},endFrame:function(){var a,b,d=this.buffer;if(this.showSpr0Hit){if(this.sprX[0]>=0&&this.sprX[0]<256&&this.sprY[0]>=0&&this.sprY[0]<240){for(a=0;a<256;++a)d[(this.sprY[0]<<8)+a]=16733525;for(a=0;a<240;++a)d[(a<<8)+this.sprX[0]]=16733525}if(this.spr0HitX>=0&&this.spr0HitX<256&&this.spr0HitY>=0&&this.spr0HitY<240){for(a=0;a<256;++a)d[(this.spr0HitY<<8)+a]=5635925;for(a=0;a<240;++a)d[(a<<8)+this.spr0HitX]=5635925}}if(this.clipToTvSize||this.f_bgClipping===
0||this.f_spClipping===0)for(b=0;b<240;++b)for(a=0;a<8;++a)d[(b<<8)+a]=0;if(this.clipToTvSize)for(b=0;b<240;++b)for(a=0;a<8;++a)d[(b<<8)+255-a]=0;if(this.clipToTvSize)for(b=0;b<8;++b)for(a=0;a<256;++a)d[(b<<8)+a]=0,d[(239-b<<8)+a]=0;this.nes.opts.showDisplay&&this.nes.ui.writeFrame(d,this.prevBuffer)},updateControlReg1:function(a){this.triggerRendering();this.f_nmiOnVblank=a>>7&1;this.f_spriteSize=a>>5&1;this.f_bgPatternTable=a>>4&1;this.f_spPatternTable=a>>3&1;this.f_addrInc=a>>2&1;this.f_nTblAddress=
a&3;this.regV=a>>1&1;this.regH=a&1;this.regS=a>>4&1},updateControlReg2:function(a){this.triggerRendering();this.f_color=a>>5&7;this.f_spVisibility=a>>4&1;this.f_bgVisibility=a>>3&1;this.f_spClipping=a>>2&1;this.f_bgClipping=a>>1&1;this.f_dispType=a&1;this.f_dispType===0&&this.palTable.setEmphasis(this.f_color);this.updatePalettes()},setStatusFlag:function(a,b){var d=1<<a;this.nes.cpu.mem[8194]=this.nes.cpu.mem[8194]&255-d|(b?d:0)},readStatusRegister:function(){var a=this.nes.cpu.mem[8194];this.firstWrite=
!0;this.setStatusFlag(this.STATUS_VBLANK,!1);return a},writeSRAMAddress:function(a){this.sramAddress=a},sramLoad:function(){return this.spriteMem[this.sramAddress]},sramWrite:function(a){this.spriteMem[this.sramAddress]=a;this.spriteRamWriteUpdate(this.sramAddress,a);++this.sramAddress;this.sramAddress%=256},scrollWrite:function(a){this.triggerRendering();this.firstWrite?(this.regHT=a>>3&31,this.regFH=a&7):(this.regFV=a&7,this.regVT=a>>3&31);this.firstWrite=!this.firstWrite},writeVRAMAddress:function(a){this.firstWrite?
(this.regFV=a>>4&3,this.regV=a>>3&1,this.regH=a>>2&1,this.regVT=this.regVT&7|(a&3)<<3):(this.triggerRendering(),this.regVT=this.regVT&24|a>>5&7,this.regHT=a&31,this.cntFV=this.regFV,this.cntV=this.regV,this.cntH=this.regH,this.cntVT=this.regVT,this.cntHT=this.regHT,this.checkSprite0(this.scanline-20));this.firstWrite=!this.firstWrite;this.cntsToAddress();this.vramAddress<8192&&this.nes.mmap.latchAccess(this.vramAddress)},vramLoad:function(){var a;this.cntsToAddress();this.regsToAddress();if(this.vramAddress<=
16127)return a=this.vramBufferedReadValue,this.vramBufferedReadValue=this.vramAddress<8192?this.vramMem[this.vramAddress]:this.mirroredLoad(this.vramAddress),this.vramAddress<8192&&this.nes.mmap.latchAccess(this.vramAddress),this.vramAddress+=this.f_addrInc==1?32:1,this.cntsFromAddress(),this.regsFromAddress(),a;a=this.mirroredLoad(this.vramAddress);this.vramAddress+=this.f_addrInc==1?32:1;this.cntsFromAddress();this.regsFromAddress();return a},vramWrite:function(a){this.triggerRendering();this.cntsToAddress();
this.regsToAddress();this.vramAddress>=8192?this.mirroredWrite(this.vramAddress,a):(this.writeMem(this.vramAddress,a),this.nes.mmap.latchAccess(this.vramAddress));this.vramAddress+=this.f_addrInc==1?32:1;this.regsFromAddress();this.cntsFromAddress()},sramDMA:function(a){a*=256;for(var b,d=this.sramAddress;d<256;++d)b=this.nes.cpu.mem[a+d],this.spriteMem[d]=b,this.spriteRamWriteUpdate(d,b);this.nes.cpu.haltCycles(513)},regsFromAddress:function(){var a=this.vramTmpAddress>>8&255;this.regFV=a>>4&7;this.regV=
a>>3&1;this.regH=a>>2&1;this.regVT=this.regVT&7|(a&3)<<3;a=this.vramTmpAddress&255;this.regVT=this.regVT&24|a>>5&7;this.regHT=a&31},cntsFromAddress:function(){var a=this.vramAddress>>8&255;this.cntFV=a>>4&3;this.cntV=a>>3&1;this.cntH=a>>2&1;this.cntVT=this.cntVT&7|(a&3)<<3;a=this.vramAddress&255;this.cntVT=this.cntVT&24|a>>5&7;this.cntHT=a&31},regsToAddress:function(){var a=(this.regFV&7)<<4;a|=(this.regV&1)<<3;a|=(this.regH&1)<<2;a|=this.regVT>>3&3;var b=(this.regVT&7)<<5;b|=this.regHT&31;this.vramTmpAddress=
(a<<8|b)&32767},cntsToAddress:function(){var a=(this.cntFV&7)<<4;a|=(this.cntV&1)<<3;a|=(this.cntH&1)<<2;a|=this.cntVT>>3&3;var b=(this.cntVT&7)<<5;b|=this.cntHT&31;this.vramAddress=(a<<8|b)&32767},incTileCounter:function(a){for(;a!==0;--a)if(++this.cntHT,this.cntHT==32&&(this.cntHT=0,++this.cntVT,this.cntVT>=30&&(++this.cntH,this.cntH==2&&(this.cntH=0,++this.cntV,this.cntV==2))))this.cntV=0,++this.cntFV,this.cntFV&=7},mirroredLoad:function(a){return this.vramMem[this.vramMirrorTable[a]]},mirroredWrite:function(a,
b){a>=16128&&a<16160?a==16128||a==16144?(this.writeMem(16128,b),this.writeMem(16144,b)):a==16132||a==16148?(this.writeMem(16132,b),this.writeMem(16148,b)):a==16136||a==16152?(this.writeMem(16136,b),this.writeMem(16152,b)):a==16140||a==16156?(this.writeMem(16140,b),this.writeMem(16156,b)):this.writeMem(a,b):a<this.vramMirrorTable.length?this.writeMem(this.vramMirrorTable[a],b):alert("Invalid VRAM address: "+a.toString(16))},triggerRendering:function(){if(this.scanline>=21&&this.scanline<=260)this.renderFramePartially(this.lastRenderedScanline+
1,this.scanline-21-this.lastRenderedScanline),this.lastRenderedScanline=this.scanline-21},renderFramePartially:function(a,b){this.f_spVisibility==1&&this.renderSpritesPartially(a,b,!0);if(this.f_bgVisibility==1){var d;d=a+b<<8;d>61440&&(d=61440);for(var e=this.buffer,f=this.bgbuffer,c=this.pixrendered,g=a<<8;g<d;++g)c[g]>255&&(e[g]=f[g])}this.f_spVisibility==1&&this.renderSpritesPartially(a,b,!1);this.validTileData=!1},renderBgScanline:function(a,b){var d=this.regS===0?0:256,e=(b<<8)-this.regFH;this.curNt=
this.ntable1[this.cntV+this.cntV+this.cntH];this.cntHT=this.regHT;this.cntH=this.regH;this.curNt=this.ntable1[this.cntV+this.cntV+this.cntH];if(b<240&&b-this.cntFV>=0){for(var f=this.cntFV<<3,c=this.scantile,g=this.attrib,i=this.ptTile,h=this.nameTable,k=this.imgPalette,m=this.pixrendered,l=a?this.bgbuffer:this.buffer,j,q,p,n=0;n<32;++n){if(b>=0){this.validTileData?(j=c[n],q=j.pix,p=g[n]):(j=i[d+h[this.curNt].getTileIndex(this.cntHT,this.cntVT)],q=j.pix,p=h[this.curNt].getAttrib(this.cntHT,this.cntVT),
c[n]=j,g[n]=p);var o=0,r=(n<<3)-this.regFH;if(r>-8)if(r<0&&(e-=r,o=-r),j.opaque[this.cntFV])for(;o<8;++o)l[e]=k[q[f+o]+p],m[e]|=256,++e;else for(;o<8;++o)j=q[f+o],j!==0&&(l[e]=k[j+p],m[e]|=256),++e}if(++this.cntHT==32)this.cntHT=0,++this.cntH,this.cntH%=2,this.curNt=this.ntable1[(this.cntV<<1)+this.cntH]}this.validTileData=!0}++this.cntFV;if(this.cntFV==8){this.cntFV=0;++this.cntVT;if(this.cntVT==30)this.cntVT=0,++this.cntV,this.cntV%=2,this.curNt=this.ntable1[(this.cntV<<1)+this.cntH];else if(this.cntVT==
32)this.cntVT=0;this.validTileData=!1}},renderSpritesPartially:function(a,b,d){if(this.f_spVisibility===1)for(var e=0;e<64;++e)if(this.bgPriority[e]==d&&this.sprX[e]>=0&&this.sprX[e]<256&&this.sprY[e]+8>=a&&this.sprY[e]<a+b)if(this.f_spriteSize===0){this.srcy1=0;this.srcy2=8;if(this.sprY[e]<a)this.srcy1=a-this.sprY[e]-1;if(this.sprY[e]+8>a+b)this.srcy2=a+b-this.sprY[e]+1;this.f_spPatternTable===0?this.ptTile[this.sprTile[e]].render(this.buffer,0,this.srcy1,8,this.srcy2,this.sprX[e],this.sprY[e]+1,
this.sprCol[e],this.sprPalette,this.horiFlip[e],this.vertFlip[e],e,this.pixrendered):this.ptTile[this.sprTile[e]+256].render(this.buffer,0,this.srcy1,8,this.srcy2,this.sprX[e],this.sprY[e]+1,this.sprCol[e],this.sprPalette,this.horiFlip[e],this.vertFlip[e],e,this.pixrendered)}else{var f=this.sprTile[e];(f&1)!==0&&(f=this.sprTile[e]-1+256);var c=0,g=8;this.sprY[e]<a&&(c=a-this.sprY[e]-1);this.sprY[e]+8>a+b&&(g=a+b-this.sprY[e]);this.ptTile[f+(this.vertFlip[e]?1:0)].render(this.buffer,0,c,8,g,this.sprX[e],
this.sprY[e]+1,this.sprCol[e],this.sprPalette,this.horiFlip[e],this.vertFlip[e],e,this.pixrendered);c=0;g=8;this.sprY[e]+8<a&&(c=a-(this.sprY[e]+8+1));this.sprY[e]+16>a+b&&(g=a+b-(this.sprY[e]+8));this.ptTile[f+(this.vertFlip[e]?0:1)].render(this.buffer,0,c,8,g,this.sprX[e],this.sprY[e]+1+8,this.sprCol[e],this.sprPalette,this.horiFlip[e],this.vertFlip[e],e,this.pixrendered)}},checkSprite0:function(a){this.spr0HitY=this.spr0HitX=-1;var b,d=this.f_spPatternTable===0?0:256,e,f,c;e=this.sprX[0];b=this.sprY[0]+
1;if(this.f_spriteSize===0){if(b<=a&&b+8>a&&e>=-7&&e<256)if(d=this.ptTile[this.sprTile[0]+d],b=this.vertFlip[0]?7-(a-b):a-b,b*=8,c=a*256+e,this.horiFlip[0])for(f=7;f>=0;--f){if(e>=0&&e<256&&c>=0&&c<61440&&this.pixrendered[c]!==0&&d.pix[b+f]!==0)return this.spr0HitX=c%256,this.spr0HitY=a,!0;++e;++c}else for(f=0;f<8;++f){if(e>=0&&e<256&&c>=0&&c<61440&&this.pixrendered[c]!==0&&d.pix[b+f]!==0)return this.spr0HitX=c%256,this.spr0HitY=a,!0;++e;++c}}else if(b<=a&&b+16>a&&e>=-7&&e<256)if(b=this.vertFlip[0]?
15-(a-b):a-b,b<8?d=this.ptTile[this.sprTile[0]+(this.vertFlip[0]?1:0)+((this.sprTile[0]&1)!==0?255:0)]:(d=this.ptTile[this.sprTile[0]+(this.vertFlip[0]?0:1)+((this.sprTile[0]&1)!==0?255:0)],this.vertFlip[0]?b=15-b:b-=8),b*=8,c=a*256+e,this.horiFlip[0])for(f=7;f>=0;--f){if(e>=0&&e<256&&c>=0&&c<61440&&this.pixrendered[c]!==0&&d.pix[b+f]!==0)return this.spr0HitX=c%256,this.spr0HitY=a,!0;++e;++c}else for(f=0;f<8;++f){if(e>=0&&e<256&&c>=0&&c<61440&&this.pixrendered[c]!==0&&d.pix[b+f]!==0)return this.spr0HitX=
c%256,this.spr0HitY=a,!0;++e;++c}return!1},writeMem:function(a,b){this.vramMem[a]=b;a<8192?(this.vramMem[a]=b,this.patternWrite(a,b)):a>=8192&&a<9152?this.nameTableWrite(this.ntable1[0],a-8192,b):a>=9152&&a<9216?this.attribTableWrite(this.ntable1[0],a-9152,b):a>=9216&&a<10176?this.nameTableWrite(this.ntable1[1],a-9216,b):a>=10176&&a<10240?this.attribTableWrite(this.ntable1[1],a-10176,b):a>=10240&&a<11200?this.nameTableWrite(this.ntable1[2],a-10240,b):a>=11200&&a<11264?this.attribTableWrite(this.ntable1[2],
a-11200,b):a>=11264&&a<12224?this.nameTableWrite(this.ntable1[3],a-11264,b):a>=12224&&a<12288?this.attribTableWrite(this.ntable1[3],a-12224,b):a>=16128&&a<16160&&this.updatePalettes()},updatePalettes:function(){var a;for(a=0;a<16;++a)this.imgPalette[a]=this.f_dispType===0?this.palTable.getEntry(this.vramMem[16128+a]&63):this.palTable.getEntry(this.vramMem[16128+a]&32);for(a=0;a<16;++a)this.sprPalette[a]=this.f_dispType===0?this.palTable.getEntry(this.vramMem[16144+a]&63):this.palTable.getEntry(this.vramMem[16144+
a]&32)},patternWrite:function(a,b){var d=Math.floor(a/16),e=a%16;e<8?this.ptTile[d].setScanline(e,b,this.vramMem[a+8]):this.ptTile[d].setScanline(e-8,this.vramMem[a-8],b)},nameTableWrite:function(a,b,d){this.nameTable[a].tile[b]=d;this.checkSprite0(this.scanline-20)},attribTableWrite:function(a,b,d){this.nameTable[a].writeAttrib(b,d)},spriteRamWriteUpdate:function(a,b){var d=Math.floor(a/4);d===0&&this.checkSprite0(this.scanline-20);a%4===0?this.sprY[d]=b:a%4==1?this.sprTile[d]=b:a%4==2?(this.vertFlip[d]=
(b&128)!==0,this.horiFlip[d]=(b&64)!==0,this.bgPriority[d]=(b&32)!==0,this.sprCol[d]=(b&3)<<2):a%4==3&&(this.sprX[d]=b)},doNMI:function(){this.setStatusFlag(this.STATUS_VBLANK,!0);this.nes.cpu.requestIrq(this.nes.cpu.IRQ_NMI)},JSON_PROPERTIES:{vramMem:"vramMem",spriteMem:"spriteMem",cntFV:"cntFV",cntV:"cntV",cntH:"cntH",cntVT:"cntVT",cntHT:"cntHT",regFV:"regFV",regV:"regV",regH:"regH",regVT:"regVT",regHT:"regHT",regFH:"regFH",regS:"regS",vramAddress:"vramAddress",vramTmpAddress:"vramTmpAddress",f_nmiOnVblank:"f_nmiOnVblank",
f_spriteSize:"f_spriteSize",f_bgPatternTable:"f_bgPatternTable",f_spPatternTable:"f_spPatternTable",f_addrInc:"f_addrInc",f_nTblAddress:"f_nTblAddress",f_color:"f_color",f_spVisibility:"f_spVisibility",f_bgVisibility:"f_bgVisibility",f_spClipping:"f_spClipping",f_bgClipping:"f_bgClipping",f_dispType:"f_dispType",vramBufferedReadValue:"vramBufferedReadValue",firstWrite:"firstWrite",currentMirroring:"currentMirroring",vramMirrorTable:"vramMirrorTable",ntable1:"ntable1",sramAddress:"sramAddress",hitSpr0:"hitSpr0",
sprPalette:"sprPalette",imgPalette:"imgPalette",curX:"curX",scanline:"scanline",lastRenderedScanline:"lastRenderedScanline",curNt:"curNt",attrib:"attrib",buffer:"buffer",bgbuffer:"bgbuffer",pixrendered:"pixrendered",requestEndFrame:"requestEndFrame",nmiOk:"nmiOk",dummyCycleToggle:"dummyCycleToggle",nmiCounter:"nmiCounter",validTileData:"validTileData",scanlineAlreadyRendered:"scanlineAlreadyRendered"},toJSON:function(){var a,b=JSNES.Utils.toJSON(this);b.nameTable=[];for(a=0;a<this.nameTable.length;++a)b.nameTable[a]=
this.nameTable[a].toJSON();b.ptTile=[];for(a=0;a<this.ptTile.length;++a)b.ptTile[a]=this.ptTile[a].toJSON();return b},fromJSON:function(a){var b;JSNES.Utils.fromJSON(this,a);for(b=0;b<this.nameTable.length;++b)this.nameTable[b].fromJSON(a.nameTable[b]);for(b=0;b<this.ptTile.length;++b)this.ptTile[b].fromJSON(a.ptTile[b]);for(b=0;b<this.spriteMem.length;++b)this.spriteRamWriteUpdate(b,this.spriteMem[b])}};
JSNES.PPU.NameTable=function(a,b,d){this.width=a;this.height=b;this.name=d;this.tile=Array(a*b);this.attrib=Array(a*b)};
JSNES.PPU.NameTable.prototype={getTileIndex:function(a,b){return this.tile[b*this.width+a]},getAttrib:function(a,b){return this.attrib[b*this.width+a]},writeAttrib:function(a,b){for(var d=a%8*4,e=Math.floor(a/8)*4,f,c,g,i=0;i<2;++i)for(var h=0;h<2;++h){f=b>>2*(i*2+h)&3;for(var k=0;k<2;++k)for(var m=0;m<2;++m)c=d+h*2+m,g=e+i*2+k,this.attrib[g*this.width+c]=f<<2&12}},toJSON:function(){return{tile:this.tile,attrib:this.attrib}},fromJSON:function(a){this.tile=a.tile;this.attrib=a.attrib}};
JSNES.PPU.PaletteTable=function(){this.curTable=Array(64);this.emphTable=Array(8);this.currentEmph=-1};
JSNES.PPU.PaletteTable.prototype={reset:function(){this.setEmphasis(0)},loadNTSCPalette:function(){this.curTable=[5395026,11796480,10485760,11599933,7602281,91,95,6208,12048,543240,26368,1196544,7153664,0,0,0,12899815,16728064,14421538,16729963,14090399,6818519,6588,21681,27227,35843,43776,2918400,10777088,0,0,0,16316664,16755516,16742785,16735173,16730354,14633471,4681215,46327,57599,58229,259115,7911470,15065624,7895160,0,0,16777215,16773822,16300216,16300248,16758527,16761855,13095423,10148607,
8973816,8650717,12122296,16119980,16777136,16308472,0,0];this.makeTables();this.setEmphasis(0)},loadPALPalette:function(){this.curTable=[5395026,11796480,10485760,11599933,7602281,91,95,6208,12048,543240,26368,1196544,7153664,0,0,0,12899815,16728064,14421538,16729963,14090399,6818519,6588,21681,27227,35843,43776,2918400,10777088,0,0,0,16316664,16755516,16742785,16735173,16730354,14633471,4681215,46327,57599,58229,259115,7911470,15065624,7895160,0,0,16777215,16773822,16300216,16300248,16758527,16761855,
13095423,10148607,8973816,8650717,12122296,16119980,16777136,16308472,0,0];this.makeTables();this.setEmphasis(0)},makeTables:function(){for(var a,b,d,e,f,c,g,i=0;i<8;++i){g=c=f=1;(i&1)!==0&&(g=f=0.75);(i&2)!==0&&(c=f=0.75);(i&4)!==0&&(g=c=0.75);this.emphTable[i]=Array(64);for(e=0;e<64;++e)d=this.curTable[e],a=Math.floor(this.getRed(d)*f),b=Math.floor(this.getGreen(d)*c),d=Math.floor(this.getBlue(d)*g),this.emphTable[i][e]=this.getRgb(a,b,d)}},setEmphasis:function(a){if(a!=this.currentEmph){this.currentEmph=
a;for(var b=0;b<64;++b)this.curTable[b]=this.emphTable[a][b]}},getEntry:function(a){return this.curTable[a]},getRed:function(a){return a>>16&255},getGreen:function(a){return a>>8&255},getBlue:function(a){return a&255},getRgb:function(a,b,d){return a<<16|b<<8|d},loadDefaultPalette:function(){this.curTable[0]=this.getRgb(117,117,117);this.curTable[1]=this.getRgb(39,27,143);this.curTable[2]=this.getRgb(0,0,171);this.curTable[3]=this.getRgb(71,0,159);this.curTable[4]=this.getRgb(143,0,119);this.curTable[5]=
this.getRgb(171,0,19);this.curTable[6]=this.getRgb(167,0,0);this.curTable[7]=this.getRgb(127,11,0);this.curTable[8]=this.getRgb(67,47,0);this.curTable[9]=this.getRgb(0,71,0);this.curTable[10]=this.getRgb(0,81,0);this.curTable[11]=this.getRgb(0,63,23);this.curTable[12]=this.getRgb(27,63,95);this.curTable[13]=this.getRgb(0,0,0);this.curTable[14]=this.getRgb(0,0,0);this.curTable[15]=this.getRgb(0,0,0);this.curTable[16]=this.getRgb(188,188,188);this.curTable[17]=this.getRgb(0,115,239);this.curTable[18]=
this.getRgb(35,59,239);this.curTable[19]=this.getRgb(131,0,243);this.curTable[20]=this.getRgb(191,0,191);this.curTable[21]=this.getRgb(231,0,91);this.curTable[22]=this.getRgb(219,43,0);this.curTable[23]=this.getRgb(203,79,15);this.curTable[24]=this.getRgb(139,115,0);this.curTable[25]=this.getRgb(0,151,0);this.curTable[26]=this.getRgb(0,171,0);this.curTable[27]=this.getRgb(0,147,59);this.curTable[28]=this.getRgb(0,131,139);this.curTable[29]=this.getRgb(0,0,0);this.curTable[30]=this.getRgb(0,0,0);this.curTable[31]=
this.getRgb(0,0,0);this.curTable[32]=this.getRgb(255,255,255);this.curTable[33]=this.getRgb(63,191,255);this.curTable[34]=this.getRgb(95,151,255);this.curTable[35]=this.getRgb(167,139,253);this.curTable[36]=this.getRgb(247,123,255);this.curTable[37]=this.getRgb(255,119,183);this.curTable[38]=this.getRgb(255,119,99);this.curTable[39]=this.getRgb(255,155,59);this.curTable[40]=this.getRgb(243,191,63);this.curTable[41]=this.getRgb(131,211,19);this.curTable[42]=this.getRgb(79,223,75);this.curTable[43]=
this.getRgb(88,248,152);this.curTable[44]=this.getRgb(0,235,219);this.curTable[45]=this.getRgb(0,0,0);this.curTable[46]=this.getRgb(0,0,0);this.curTable[47]=this.getRgb(0,0,0);this.curTable[48]=this.getRgb(255,255,255);this.curTable[49]=this.getRgb(171,231,255);this.curTable[50]=this.getRgb(199,215,255);this.curTable[51]=this.getRgb(215,203,255);this.curTable[52]=this.getRgb(255,199,255);this.curTable[53]=this.getRgb(255,199,219);this.curTable[54]=this.getRgb(255,191,179);this.curTable[55]=this.getRgb(255,
219,171);this.curTable[56]=this.getRgb(255,231,163);this.curTable[57]=this.getRgb(227,255,163);this.curTable[58]=this.getRgb(171,243,191);this.curTable[59]=this.getRgb(179,255,207);this.curTable[60]=this.getRgb(159,255,243);this.curTable[61]=this.getRgb(0,0,0);this.curTable[62]=this.getRgb(0,0,0);this.curTable[63]=this.getRgb(0,0,0);this.makeTables();this.setEmphasis(0)}};
JSNES.PPU.Tile=function(){this.pix=Array(64);this.c=this.tpri=this.palIndex=this.incY=this.incX=this.h=this.w=this.y=this.x=this.tIndex=this.fbIndex=null;this.initialized=!1;this.opaque=Array(8)};
JSNES.PPU.Tile.prototype={setBuffer:function(a){for(this.y=0;this.y<8;++this.y)this.setScanline(this.y,a[this.y],a[this.y+8])},setScanline:function(a,b,d){this.initialized=!0;this.tIndex=a<<3;for(this.x=0;this.x<8;++this.x)this.pix[this.tIndex+this.x]=(b>>7-this.x&1)+((d>>7-this.x&1)<<1),this.pix[this.tIndex+this.x]===0&&(this.opaque[a]=!1)},render:function(a,b,d,e,f,c,g,i,h,k,m,l,j){if(!(c<-7||c>=256||g<-7||g>=240))if(this.w=e-b,this.h=f-d,c<0&&(b-=c),c+e>=256&&(e=256-c),g<0&&(d-=g),g+f>=240&&(f=
240-g),!k&&!m){this.fbIndex=(g<<8)+c;for(this.y=this.tIndex=0;this.y<8;++this.y){for(this.x=0;this.x<8;++this.x){if(this.x>=b&&this.x<e&&this.y>=d&&this.y<f&&(this.palIndex=this.pix[this.tIndex],this.tpri=j[this.fbIndex],this.palIndex!==0&&l<=(this.tpri&255)))a[this.fbIndex]=h[this.palIndex+i],this.tpri=this.tpri&3840|l,j[this.fbIndex]=this.tpri;++this.fbIndex;++this.tIndex}this.fbIndex-=8;this.fbIndex+=256}}else if(k&&!m){this.fbIndex=(g<<8)+c;this.tIndex=7;for(this.y=0;this.y<8;++this.y){for(this.x=
0;this.x<8;++this.x){if(this.x>=b&&this.x<e&&this.y>=d&&this.y<f&&(this.palIndex=this.pix[this.tIndex],this.tpri=j[this.fbIndex],this.palIndex!==0&&l<=(this.tpri&255)))a[this.fbIndex]=h[this.palIndex+i],this.tpri=this.tpri&3840|l,j[this.fbIndex]=this.tpri;++this.fbIndex;--this.tIndex}this.fbIndex-=8;this.fbIndex+=256;this.tIndex+=16}}else if(m&&!k){this.fbIndex=(g<<8)+c;this.tIndex=56;for(this.y=0;this.y<8;++this.y){for(this.x=0;this.x<8;++this.x){if(this.x>=b&&this.x<e&&this.y>=d&&this.y<f&&(this.palIndex=
this.pix[this.tIndex],this.tpri=j[this.fbIndex],this.palIndex!==0&&l<=(this.tpri&255)))a[this.fbIndex]=h[this.palIndex+i],this.tpri=this.tpri&3840|l,j[this.fbIndex]=this.tpri;++this.fbIndex;++this.tIndex}this.fbIndex-=8;this.fbIndex+=256;this.tIndex-=16}}else{this.fbIndex=(g<<8)+c;this.tIndex=63;for(this.y=0;this.y<8;++this.y){for(this.x=0;this.x<8;++this.x){if(this.x>=b&&this.x<e&&this.y>=d&&this.y<f&&(this.palIndex=this.pix[this.tIndex],this.tpri=j[this.fbIndex],this.palIndex!==0&&l<=(this.tpri&
255)))a[this.fbIndex]=h[this.palIndex+i],this.tpri=this.tpri&3840|l,j[this.fbIndex]=this.tpri;++this.fbIndex;--this.tIndex}this.fbIndex-=8;this.fbIndex+=256}}},isTransparent:function(a,b){return this.pix[(b<<3)+a]===0},toJSON:function(){return{opaque:this.opaque,pix:this.pix}},fromJSON:function(a){this.opaque=a.opaque;this.pix=a.pix}};JSNES.ROM=function(a){this.nes=a;this.mapperName=Array(92);for(a=0;a<92;++a)this.mapperName[a]="Unknown Mapper";this.mapperName[0]="Direct Access";this.mapperName[1]="Nintendo MMC1";this.mapperName[2]="UNROM";this.mapperName[3]="CNROM";this.mapperName[4]="Nintendo MMC3";this.mapperName[5]="Nintendo MMC5";this.mapperName[6]="FFE F4xxx";this.mapperName[7]="AOROM";this.mapperName[8]="FFE F3xxx";this.mapperName[9]="Nintendo MMC2";this.mapperName[10]="Nintendo MMC4";this.mapperName[11]="Color Dreams Chip";
this.mapperName[12]="FFE F6xxx";this.mapperName[15]="100-in-1 switch";this.mapperName[16]="Bandai chip";this.mapperName[17]="FFE F8xxx";this.mapperName[18]="Jaleco SS8806 chip";this.mapperName[19]="Namcot 106 chip";this.mapperName[20]="Famicom Disk System";this.mapperName[21]="Konami VRC4a";this.mapperName[22]="Konami VRC2a";this.mapperName[23]="Konami VRC2a";this.mapperName[24]="Konami VRC6";this.mapperName[25]="Konami VRC4b";this.mapperName[32]="Irem G-101 chip";this.mapperName[33]="Taito TC0190/TC0350";
this.mapperName[34]="32kB ROM switch";this.mapperName[64]="Tengen RAMBO-1 chip";this.mapperName[65]="Irem H-3001 chip";this.mapperName[66]="GNROM switch";this.mapperName[67]="SunSoft3 chip";this.mapperName[68]="SunSoft4 chip";this.mapperName[69]="SunSoft5 FME-7 chip";this.mapperName[71]="Camerica chip";this.mapperName[78]="Irem 74HC161/32-based";this.mapperName[91]="Pirate HK-SF3 chip"};
JSNES.ROM.prototype={VERTICAL_MIRRORING:0,HORIZONTAL_MIRRORING:1,FOURSCREEN_MIRRORING:2,SINGLESCREEN_MIRRORING:3,SINGLESCREEN_MIRRORING2:4,SINGLESCREEN_MIRRORING3:5,SINGLESCREEN_MIRRORING4:6,CHRROM_MIRRORING:7,header:null,rom:null,vrom:null,vromTile:null,romCount:null,vromCount:null,mirroring:null,batteryRam:null,trainer:null,fourScreen:null,mapperType:null,valid:!1,load:function(a){var b,d;if(a.indexOf("NES\u001a")===-1)this.nes.ui.updateStatus("Not a valid NES ROM.");else{this.header=Array(16);
for(b=0;b<16;++b)this.header[b]=a.charCodeAt(b)&255;this.romCount=this.header[4];this.vromCount=this.header[5]*2;this.mirroring=(this.header[6]&1)!==0?1:0;this.batteryRam=(this.header[6]&2)!==0;this.trainer=(this.header[6]&4)!==0;this.fourScreen=(this.header[6]&8)!==0;this.mapperType=this.header[6]>>4|this.header[7]&240;d=!1;for(b=8;b<16;++b)if(this.header[b]!==0){d=!0;break}d&&(this.mapperType&=15);this.rom=Array(this.romCount);var e=16;for(b=0;b<this.romCount;++b){this.rom[b]=Array(16384);for(d=
0;d<16384;++d){if(e+d>=a.length)break;this.rom[b][d]=a.charCodeAt(e+d)&255}e+=16384}this.vrom=Array(this.vromCount);for(b=0;b<this.vromCount;++b){this.vrom[b]=Array(4096);for(d=0;d<4096;++d){if(e+d>=a.length)break;this.vrom[b][d]=a.charCodeAt(e+d)&255}e+=4096}this.vromTile=Array(this.vromCount);for(b=0;b<this.vromCount;++b){this.vromTile[b]=Array(256);for(d=0;d<256;++d)this.vromTile[b][d]=new JSNES.PPU.Tile}for(a=0;a<this.vromCount;++a)for(b=0;b<4096;++b)d=b>>4,e=b%16,e<8?this.vromTile[a][d].setScanline(e,
this.vrom[a][b],this.vrom[a][b+8]):this.vromTile[a][d].setScanline(e-8,this.vrom[a][b-8],this.vrom[a][b]);this.valid=!0}},getMirroringType:function(){if(this.fourScreen)return this.FOURSCREEN_MIRRORING;if(this.mirroring===0)return this.HORIZONTAL_MIRRORING;return this.VERTICAL_MIRRORING},getMapperName:function(){if(this.mapperType>=0&&this.mapperType<this.mapperName.length)return this.mapperName[this.mapperType];return"Unknown Mapper, "+this.mapperType},mapperSupported:function(){return typeof JSNES.Mappers[this.mapperType]!==
"undefined"},createMapper:function(){return this.mapperSupported()?new JSNES.Mappers[this.mapperType](this.nes):(this.nes.ui.updateStatus("This ROM uses a mapper not supported by JSNES: "+this.getMapperName()+"("+this.mapperType+")"),null)}};JSNES.DummyUI=function(a){this.nes=a;this.enable=function(){};this.updateStatus=function(){};this.writeAudio=function(){};this.writeFrame=function(){}};
typeof jQuery!=="undefined"&&function(a){a.fn.JSNESUI=function(b){var d=this,e=function(e){var c=this;c.nes=e;c.root=a("<div></div>");c.screen=a('<canvas class="nes-screen" width="256" height="240"></canvas>').appendTo(c.root);c.screen[0].getContext?(c.romContainer=a('<div class="nes-roms"></div>').appendTo(c.root),c.romSelect=a("<select></select>").appendTo(c.romContainer),c.controls=a('<div class="nes-controls"></div>').appendTo(c.root),c.buttons={pause:a('<input type="button" value="pause" class="nes-pause" disabled="disabled">').appendTo(c.controls),
restart:a('<input type="button" value="restart" class="nes-restart" disabled="disabled">').appendTo(c.controls),sound:a('<input type="button" value="enable sound" class="nes-enablesound">').appendTo(c.controls),zoom:a('<input type="button" value="zoom in" class="nes-zoom">').appendTo(c.controls)},c.status=a('<p class="nes-status">Booting up...</p>').appendTo(c.root),c.root.appendTo(d),c.romSelect.change(function(){c.loadROM()}),c.buttons.pause.click(function(){c.nes.isRunning?(c.nes.stop(),c.updateStatus("Paused"),
c.buttons.pause.attr("value","resume")):(c.nes.start(),c.buttons.pause.attr("value","pause"))}),c.buttons.restart.click(function(){c.nes.reloadRom();c.nes.start()}),c.buttons.sound.click(function(){c.nes.opts.emulateSound?(c.nes.opts.emulateSound=!1,c.buttons.sound.attr("value","enable sound")):(c.nes.opts.emulateSound=!0,c.buttons.sound.attr("value","disable sound"))}),c.zoomed=!1,c.buttons.zoom.click(function(){c.zoomed?(c.screen.animate({width:"256px",height:"240px"}),c.buttons.zoom.attr("value",
"zoom in"),c.zoomed=!1):(c.screen.animate({width:"512px",height:"480px"}),c.buttons.zoom.attr("value","zoom out"),c.zoomed=!0)}),a.offset&&c.screen.mousedown(function(a){if(c.nes.mmap)c.nes.mmap.mousePressed=!0,c.nes.mmap.mouseX=a.pageX-c.screen.offset().left,c.nes.mmap.mouseY=a.pageY-c.screen.offset().top}).mouseup(function(){setTimeout(function(){if(c.nes.mmap)c.nes.mmap.mousePressed=!1,c.nes.mmap.mouseX=0,c.nes.mmap.mouseY=0},500)}),typeof b!="undefined"&&c.setRoms(b),c.canvasContext=c.screen[0].getContext("2d"),
c.canvasContext.getImageData?(c.canvasImageData=c.canvasContext.getImageData(0,0,256,240),c.resetCanvas(),a(document).bind("keydown",function(a){c.nes.keyboard.keyDown(a)}).bind("keyup",function(a){c.nes.keyboard.keyUp(a)}).bind("keypress",function(a){c.nes.keyboard.keyPress(a)}),c.dynamicaudio=new DynamicAudio({swf:e.opts.swfPath+"dynamicaudio.swf"})):d.html("Your browser doesn't support writing pixels directly to the <code>&lt;canvas&gt;</code> tag. Try the latest versions of Google Chrome, Safari, Opera or Firefox!")):
d.html("Your browser doesn't support the <code>&lt;canvas&gt;</code> tag. Try Google Chrome, Safari, Opera or Firefox!")};e.prototype={loadROM:function(){var b=this;b.updateStatus("Downloading...");a.ajax({url:escape(b.romSelect.val()),xhr:function(){var c=a.ajaxSettings.xhr();typeof c.overrideMimeType!=="undefined"&&c.overrideMimeType("text/plain; charset=x-user-defined");return b.xhr=c},complete:function(a){JSNES.Utils.isIE()?(a=JSNESBinaryToArray(a.responseBody).toArray(),a=String.fromCharCode.apply(void 0,
a)):a=a.responseText;b.nes.loadRom(a);b.nes.start();b.enable()}})},resetCanvas:function(){this.canvasContext.fillStyle="black";this.canvasContext.fillRect(0,0,256,240);for(var a=3;a<this.canvasImageData.data.length-3;a+=4)this.canvasImageData.data[a]=255},enable:function(){this.buttons.pause.attr("disabled",null);this.nes.isRunning?this.buttons.pause.attr("value","pause"):this.buttons.pause.attr("value","resume");this.buttons.restart.attr("disabled",null);this.nes.opts.emulateSound?this.buttons.sound.attr("value",
"disable sound"):this.buttons.sound.attr("value","enable sound")},updateStatus:function(a){this.status.text(a)},setRoms:function(b){this.romSelect.children().remove();a("<option>Select a ROM...</option>").appendTo(this.romSelect);for(var c in b)if(b.hasOwnProperty(c)){for(var d=a("<optgroup></optgroup>").attr("label",c),e=0;e<b[c].length;++e)a("<option>"+b[c][e][0]+"</option>").attr("value",b[c][e][1]).appendTo(d);this.romSelect.append(d)}},writeAudio:function(a){return this.dynamicaudio.writeInt(a)},
writeFrame:function(a,b){var d=this.canvasImageData.data,e,h,k;for(h=0;h<61440;++h)e=a[h],e!=b[h]&&(k=h*4,d[k]=e&255,d[k+1]=e>>8&255,d[k+2]=e>>16&255,b[h]=e);this.canvasContext.putImageData(this.canvasImageData,0,0)}};return e}}(jQuery);
