var roms_list = {
    "Working": new Array(
        'Bubble Bobble (U).nes',
        'Contra (U) [!].nes',
        'Donkey Kong (JU).nes',
        'Dr. Mario (JU).nes',
        'Duck Hunt (JUE) [!].nes',
        'Golf (JU).nes',
        'Legend of Zelda, The (U) (PRG1).nes',
        'Lemmings (U).nes',
        'Lifeforce (U).nes',
        'Mario Bros. (JU) [!].nes',
        'Mega Man (U).nes',
        'Pac-Man (U) [!].nes',
        'Super Mario Bros. (JU) (PRG0) [!].nes',
        'Tennis (JU) [!].nes',
        'Tetris (U) [!].nes',
        'Tetris 2 (U) [!].nes',
        'Zelda II - The Adventure of Link (U).nes'
    ),
    
    "Nearly Working": new Array(
        'Super Mario Bros. 3 (U) (PRG1) [!].nes'
    )
    
    /*
    "Broken": new Array(
        'Mega Man 2 (U).nes',
        'Metroid (U) [!].nes'
    )
    "Untested": new Array(
        '10-Yard Fight (U).nes',
        '1942 (JU) [!].nes',
        '1943 - The Battle of Midway (U).nes',
        '3-D Battles of World Runner, The (U).nes',
        '720 (U).nes',
        '8 Eyes (U).nes',
        'Abadox (U).nes',
        'Action 52 (U) [!].nes',
        'Addams Family, The (U).nes',
        'Addams Family, The - Pugsley\'s Scavenger Hunt (U).nes',
        'Advanced Dungeons & Dragons - Dragon Strike (U).nes',
        'Advanced Dungeons & Dragons - Heroes of the Lance (U).nes',
        'Advanced Dungeons & Dragons - Hillsfar (U) [!].nes',
        'Advanced Dungeons & Dragons - Pool of Radiance (U).nes',
        'Adventures in the Magic Kingdom (U).nes',
        'Adventures of Bayou Billy, The (U).nes',
        'Adventures of Captain Comic, The (U).nes',
        'Adventures of Dino Riki, The (U).nes',
        'Adventures of Lolo (U) [!].nes',
        'Adventures of Lolo 2 (U).nes',
        'Adventures of Lolo 3 (U).nes',
        'Adventures of Rad Gravity, The (U).nes',
        'Adventures of Rocky and Bullwinkle and Friends, The (U).nes',
        'Adventures of Tom Sawyer (U).nes',
        'After Burner (U).nes',
        'Air Fortress (U).nes',
        'Airwolf (U).nes',
        'Al Unser Jr. Turbo Racing (U).nes',
        'Aladdin (Unl).nes',
        'Alfred Chicken (U).nes',
        'Alien 3 (U).nes',
        'Alien Syndrome (U).nes',
        'All-Pro Basketball (U).nes',
        'Alpha Mission (U).nes',
        'Amagon (U).nes',
        'American Gladiators (U).nes',
        'Anticipation (U).nes',
        'Arch Rivals - A Basket Brawl! (U).nes',
        'Archon (U).nes',
        'Arkanoid (U).nes',
        'Arkista\'s Ring (U) [!].nes',
        'Astyanax (U).nes',
        'Athena (U).nes',
        'Athletic World (U).nes',
        'Attack of the Killer Tomatoes (U).nes',
        'Baby Boomer (U).nes',
        'Back to the Future (U).nes',
        'Back to the Future II & III (U).nes',
        'Bad Dudes (U).nes',
        'Bad News Baseball (U).nes',
        'Bad Street Brawler (U).nes',
        'Balloon Fight (JU) [!].nes',
        'Bandai Golf - Challenge Pebble Beach (U).nes',
        'Bandit Kings of Ancient China (U).nes',
        'Barbie (U) (Rev 3).nes',
        'Bard\'s Tale, The - Tales of the Unknown (U) [!].nes',
        'Barker Bill\'s Trick Shooting (U).nes',
        'Base Wars (U).nes',
        'Baseball (UE) [!].nes',
        'Baseball Simulator 1.000 (U).nes',
        'Baseball Stars (U).nes',
        'Baseball Stars II (U).nes',
        'Bases Loaded (U).nes',
        'Bases Loaded 3 (U).nes',
        'Bases Loaded 4 (U).nes',
        'Bases Loaded II (U).nes',
        'Batman (U).nes',
        'Batman - Return of the Joker (U).nes',
        'Batman Returns (U).nes',
        'Battle Chess (U).nes',
        'Battle of Olympus, The (U).nes',
        'Battle Tank (U).nes',
        'Battleship (U).nes',
        'Battletoads & Double Dragon - The Ultimate Team (U).nes',
        'Battletoads (U).nes',
        'Bee 52 (U).nes',
        'Beetlejuice (U) [!].nes',
        'Best of the Best - Championship Karate (U).nes',
        'Bible Adventures (U) (V1.3).nes',
        'Bible Buffet (U).nes',
        'Big Bird\'s Hide & Speak (U).nes',
        'Big Nose Freaks Out (U).nes',
        'Big Nose the Caveman (U).nes',
        'Bigfoot (U).nes',
        'Bill & Ted\'s Excellent Video Game Adventure (U).nes',
        'Bill Elliott\'s NASCAR Challenge (U).nes',
        'Bionic Commando (U) [!].nes',
        'Black Bass USA, The (U).nes',
        'Blackjack (U).nes',
        'Blades of Steel (U).nes',
        'Blaster Master (U).nes',
        'Blue Marlin, The (U).nes',
        'Blues Brothers, The (U).nes',
        'Bo Jackson Baseball (U).nes',
        'Bomberman (U).nes',
        'Bomberman II (U).nes',
        'Bonk\'s Adventure (U).nes',
        'Boulder Dash (U).nes',
        'Boy and His Blob, A - Trouble on Blobolonia (U).nes',
        'Bram Stoker\'s Dracula (U).nes',
        'Break Time - The National Pool Tour (U).nes',
        'BreakThru (U).nes',
        'Bubble Bath Babes (UE) [!].nes',
        'Bubble Bobble (U).nes',
        'Bubble Bobble Part 2 (U).nes',
        'Bucky O\'Hare (U) [!].nes',
        'Bugs Bunny Birthday Blowout, The (U).nes',
        'Bugs Bunny Crazy Castle, The (U).nes',
        'Bugs Bunny Fun House (U) (Prototype).nes',
        'Bump\'n\'Jump (U).nes',
        'Burai Fighter (U).nes',
        'Burger Time (U) [!].nes',
        'Cabal (U).nes',
        'Caesars Palace (U).nes',
        'California Games (U).nes',
        'California Raisins - The Grape Escape (U).nes',
        'Caltron 6-in-1 (U).nes',
        'Captain America and The Avengers (U).nes',
        'Captain Planet and The Planeteers (U).nes',
        'Captain Skyhawk (U).nes',
        'Casino Kid (U).nes',
        'Casino Kid 2 (U).nes',
        'Castelian (U).nes',
        'Castle of Deceit (U).nes',
        'Castle of Dragon (U).nes',
        'Castlequest (U).nes',
        'Castlevania (U) (PRG1).nes',
        'Castlevania II - Simon\'s Quest (U).nes',
        'Castlevania III - Dracula\'s Curse (U) [!].nes',
        'Caveman Games (U).nes',
        'Challenge of the Dragon (U).nes',
        'Championship Bowling (U) [!].nes',
        'Championship Pool (U).nes',
        'Cheetah Men II (U).nes',
        'Chessmaster, The (U).nes',
        'Chiller (U) [!].nes',
        'Chip \'n Dale Rescue Rangers (U) [!].nes',
        'Chip \'n Dale Rescue Rangers 2 (U).nes',
        'Chubby Cherub (U).nes',
        'Circus Caper (U).nes',
        'City Connection (U).nes',
        'Clash at Demonhead (U).nes',
        'Classic Concentration (U).nes',
        'Cliffhanger (U).nes',
        'Clu Clu Land (JU).nes',
        'Cobra Command (U).nes',
        'Cobra Triangle (U).nes',
        'Code Name - Viper (U).nes',
        'Color A Dinosaur (U).nes',
        'Commando (U).nes',
        'Conan (U).nes',
        'Conflict (U) [!].nes',
        'Conquest of the Crystal Palace (U).nes',
        'Contra Force (U).nes',
        'Cool World (U).nes',
        'Cowboy Kid (U).nes',
        'Crash \'n the Boys - Street Challenge (U).nes',
        'Crystal Mines (U).nes',
        'Crystalis (U).nes',
        'Cyberball (U).nes',
        'Cybernoid - The Fighting Machine (U).nes',
        'Danny Sullivan\'s Indy Heat (U).nes',
        'Darkman (U).nes',
        'Darkwing Duck (U).nes',
        'Dash Galaxy in the Alien Asylum (U).nes',
        'Day Dreamin\' Davey (U).nes',
        'Days of Thunder (U).nes',
        'Deadly Towers (U).nes',
        'Death Race (U).nes',
        'Deathbots (U).nes',
        'Defender II (U).nes',
        'Defender of the Crown (U).nes',
        'Defenders of Dynatron City (U).nes',
        'Deja Vu (U).nes',
        'Demon Sword (U).nes',
        'Desert Commander (U).nes',
        'Destination Earthstar (U).nes',
        'Destiny of an Emperor (U).nes',
        'Dick Tracy (U).nes',
        'Die Hard (U).nes',
        'Dig Dug II (U) [!].nes',
        'Digger - The Legend of the Lost City (U).nes',
        'Dirty Harry (U).nes',
        'Dizzy The Adventurer (U).nes',
        'Donkey Kong 3 (JUE).nes',
        'Donkey Kong Classics (U) [!].nes',
        'Donkey Kong Jr. (JU).nes',
        'Donkey Kong Jr. Math (U).nes',
        'Double Dare (U).nes',
        'Double Dragon (U).nes',
        'Double Dragon II - The Revenge (U).nes',
        'Double Dragon III - The Sacred Stones (U).nes',
        'Double Dribble (U) (PRG1) [!].nes',
        'Double Strike (U) (V1.1).nes',
        'Dr. Chaos (U).nes',
        'Dr. Jekyll and Mr. Hyde (U).nes',
        'Dragon Fighter (U).nes',
        'Dragon Power (U).nes',
        'Dragon Spirit - The New Legend (U).nes',
        'Dragon Warrior (U) (PRG1).nes',
        'Dragon Warrior II (U).nes',
        'Dragon Warrior III (U).nes',
        'Dragon Warrior IV (U).nes',
        'Dragon\'s Lair (U).nes',
        'Duck Tales (U).nes',
        'Duck Tales 2 (U).nes',
        'Dudes With Attitude (U).nes',
        'Dungeon Magic - Sword of the Elements (U).nes',
        'Dusty Diamond\'s All-Star Softball (U).nes',
        'Dynowarz - Destruction of Spondylus (U).nes',
        'Elevator Action (U).nes',
        'Eliminator Boat Duel (U).nes',
        'Excitebike (JU) [!].nes',
        'Exodus (U) (V4.0) [!].nes',
        'F-117A Stealth Fighter (U) [!].nes',
        'F-15 City War (U).nes',
        'F-15 Strike Eagle (U).nes',
        'Family Feud (U).nes',
        'Fantastic Adventures of Dizzy, The (U).nes',
        'Fantasy Zone (U).nes',
        'Faria - A World of Mystery and Danger! (U).nes',
        'Faxanadu (U).nes',
        'Felix the Cat (U).nes',
        'Ferrari - Grand Prix Challenge (U) [!].nes',
        'Fester\'s Quest (U) [!].nes',
        'Final Fantasy (U) [!].nes',
        'Fire \'n Ice (U).nes',
        'Fire Hawk (Unl).nes',
        'Firehouse Rescue (U).nes',
        'Fist of the North Star (U).nes',
        'Flight of the Intruder (U).nes',
        'Flintstones, The - The Rescue of Dino & Hoppy (U).nes',
        'Flintstones, The - The Surprise at Dinosaur Peak! (U).nes',
        'Flying Dragon - The Secret Scroll (U).nes',
        'Flying Warriors (U).nes',
        'Formula One - Built To Win (U) [o1].nes',
        'Frankenstein - The Monster Returns (U).nes',
        'Freedom Force (U) [!].nes',
        'Friday the 13th (U).nes',
        'Fun House (U).nes',
        'G.I. Joe (U).nes',
        'G.I. Joe - The Atlantis Factor (U).nes',
        'Galaga (U).nes',
        'Galaxy 5000 (U).nes',
        'Gargoyle\'s Quest II - The Demon Darkness (U).nes',
        'Gauntlet (U) [!].nes',
        'Gauntlet II (U).nes',
        'Gemfire (U).nes',
        'Genghis Khan (U).nes',
        'George Foreman\'s KO Boxing (U).nes',
        'Ghostbusters (U).nes',
        'Ghostbusters 2 (U).nes',
        'Ghosts\'n Goblins (U) [!].nes',
        'Ghoul School (U).nes',
        'Gilligan\'s Island (U).nes',
        'Goal! (U).nes',
        'Goal! Two (U).nes',
        'Godzilla - Monster of Monsters! (U).nes',
        'Godzilla 2 - War of the Monsters (U).nes',
        'Gold Medal Challenge \'92 (U).nes',
        'Golf Grand Slam (U).nes',
        'Golgo 13 - Top Secret Episode (U).nes',
        'Goonies II, The (U).nes',
        'Gotcha! - The Sport! (U).nes',
        'Gradius (U).nes',
        'Great Waldo Search, The (U).nes',
        'Greg Norman\'s Golf Power (U).nes',
        'Gremlins 2 - The New Batch (U).nes',
        'Guardian Legend, The (U).nes',
        'Guerrilla War (U).nes',
        'Gumshoe (UE).nes',
        'Gun Nac (U).nes',
        'Gun.Smoke (U).nes',
        'Gyromite (JUE).nes',
        'Gyruss (U).nes',
        'Harlem Globetrotters (U).nes',
        'Hatris (U).nes',
        'Heavy Barrel (U).nes',
        'Heavy Shreddin\' (U).nes',
        'High Speed (U).nes',
        'Hogan\'s Alley (JU) [!].nes',
        'Hollywood Squares (U).nes',
        'Home Alone (U) [!].nes',
        'Home Alone 2 - Lost in New York (U).nes',
        'Hook (U).nes',
        'Hoops (U).nes',
        'Hot Slot (UE).nes',
        'Hudson Hawk (U).nes',
        'Hudson\'s Adventure Island (U).nes',
        'Hudson\'s Adventure Island II (U).nes',
        'Hudson\'s Adventure Island III (U).nes',
        'Hunt for Red October, The (U).nes',
        'Hydlide (U).nes',
        'I Can Remember (U).nes',
        'Ice Climber (U) [!].nes',
        'Ice Hockey (U) [!].nes',
        'Ikari III - The Rescue (U).nes',
        'Ikari Warriors (U) (PRG1) [!].nes',
        'Ikari Warriors II - Victory Road (U).nes',
        'Image Fight (U).nes',
        'Immortal, The (U).nes',
        'Impossible Mission II (U).nes',
        'Incredible Crash Dummies, The (U).nes',
        'Indiana Jones and the Last Crusade (U) (Taito).nes',
        'Indiana Jones and the Temple of Doom (U) (Tengen).nes',
        'Infiltrator (U).nes',
        'Iron Tank (U).nes',
        'Ironsword - Wizards & Warriors II (U).nes',
        'Isolated Warrior (U).nes',
        'Ivan Ironman Stewart\'s Super Off-Road (U).nes',
        'Jack Nicklaus\' Greatest 18 Holes of Major Championship Golf (U).nes',
        'Jackal (U).nes',
        'Jackie Chan\'s Action Kung Fu (U).nes',
        'James Bond Jr (U).nes',
        'Jaws (U) [!].nes',
        'Jeopardy! (U).nes',
        'Jeopardy! 25th Anniversary Edition (U).nes',
        'Jeopardy! Junior Edition (U).nes',
        'Jetsons, The - Cogswell\'s Caper! (U).nes',
        'Jimmy Connor\'s Tennis (U).nes',
        'Joe & Mac (U).nes',
        'John Elway\'s Quarterback (U).nes',
        'Joshua (U) (V6.0) [!].nes',
        'Journey to Silius (U).nes',
        'Joust (U).nes',
        'Jungle Book, The (U).nes',
        'Jurassic Park (U).nes',
        'Kabuki - Quantum Fighter (U).nes',
        'Karate Champ (U).nes',
        'Karate Kid, The (U).nes',
        'Karnov (U).nes',
        'Kick Master (U).nes',
        'Kickle Cubicle (U).nes',
        'Kid Icarus (UE).nes',
        'Kid Klown (U).nes',
        'Kid Kool (U).nes',
        'Kid Niki - Radical Ninja (U) (PRG1) [!].nes',
        'King Neptune\'s Adventure (U).nes',
        'King of Kings, The (U) (V1.2) [!].nes',
        'King\'s Knight (U).nes',
        'King\'s Quest V (U).nes',
        'Kings of the Beach (U).nes',
        'Kirby\'s Adventure (U) (PRG1) [!].nes',
        'Kiwi Kraze (U).nes',
        'Klash Ball (U).nes',
        'Klax (U).nes',
        'Knight Rider (U).nes',
        'Krazy Kreatures (U).nes',
        'Krion Conquest, The (U).nes',
        'Krusty\'s Fun House (U).nes',
        'Kung Fu (U) [!].nes',
        'Kung-Fu Heroes (U).nes',
        'L\'Empereur (U).nes',
        'Laser Invasion (U).nes',
        'Last Action Hero (U) [!].nes',
        'Last Ninja, The (U).nes',
        'Last Starfighter, The (U).nes',
        'Lee Trevino\'s Fighting Golf (U).nes',
        'Legacy of the Wizard (U).nes',
        'Legend of Kage, The (U).nes',
        'Legend of the Ghost Lion (U).nes',
        'Legendary Wings (U).nes',
        'Legends of the Diamond (U).nes',
        'Lethal Weapon (U).nes',
        'Lifeforce (U).nes',
        'Linus Spacehead\'s Cosmic Crusade (Aladdin) (U).nes',
        'Little League Baseball - Championship Series (U).nes',
        'Little Mermaid, The (U).nes',
        'Little Nemo - The Dream Master (U).nes',
        'Little Ninja Brothers (U).nes',
        'Little Samson (U).nes',
        'Lode Runner (U).nes',
        'Lone Ranger, The (U).nes',
        'Loopz (U).nes',
        'Low G Man (U) [!].nes',
        'Lunar Pool (U).nes',
        'M.C. Kids (U).nes',
        'M.U.L.E. (U).nes',
        'M.U.S.C.L.E. (U).nes',
        'Mach Rider (JU).nes',
        'Mad Max (U) [!].nes',
        'Mafat Conspiracy - Golgo 13 (U).nes',
        'Magic Darts (U).nes',
        'Magic Johnson\'s Fast Break (U).nes',
        'Magic of Scheherazade, The (U).nes',
        'Magician (U).nes',
        'Magmax (U).nes',
        'Major League Baseball (U).nes',
        'Maniac Mansion (U).nes',
        'Mappy-Land (U).nes',
        'Marble Madness (U).nes',
        'Mario is Missing! (U).nes',
        'Mario\'s Time Machine! (U).nes',
        'Marvel\'s X-Men (U).nes',
        'Master Chu & The Drunkard Hu (U).nes',
        'Mechanized Attack (U).nes',
        'Mega Man (U).nes',
        'Mega Man 2 (U).nes',
        'Mega Man 3 (U) [!].nes',
        'Mega Man 4 (U).nes',
        'Mega Man 5 (U).nes',
        'Mega Man 6 (U).nes',
        'Menace Beach (U).nes',
        'Mendel Palace (U).nes',
        'Mermaids of Atlantis (U).nes',
        'Metal Fighter (U).nes',
        'Metal Gear (U).nes',
        'Metal Mech (U).nes',
        'Metal Storm (U).nes',
        'metalgear2.nes',
        'Metroid (U) [!].nes',
        'Michael Andretti\'s World Grand Prix (U).nes',
        'Mickey Mousecapade (U).nes',
        'Mickey\'s Adventures in Numberland (U).nes',
        'Mickey\'s Safari in Letterland (U).nes',
        'Micro Machines (U).nes',
        'MiG 29 - Soviet Fighter (U).nes',
        'Might and Magic (U).nes',
        'Mighty Bomb Jack (U).nes',
        'Mighty Final Fight (U).nes',
        'Mike Tyson\'s Punch-Out!! (U) (PRG1).nes',
        'Millipede (U).nes',
        'Milon\'s Secret Castle (U).nes',
        'Miracle Piano Teaching System, The (U).nes',
        'Mission Cobra (U).nes',
        'Mission Impossible (U).nes',
        'Monopoly (U).nes',
        'Monster In My Pocket (U).nes',
        'Monster Party (U).nes',
        'Monster Truck Rally (U).nes',
        'Moon Ranger (U).nes',
        'Motor City Patrol (U).nes',
        'Ms. Pac-Man (U) (Tengen).nes',
        'Muppet Adventure - Chaos at the Carnival (U).nes',
        'Mutant Virus, The (U).nes',
        'Mystery Quest (U).nes',
        'NARC (U).nes',
        'NES Open Tournament Golf (U).nes',
        'NES Play Action Football (U).nes',
        'NFL Football (U).nes',
        'Nigel Mansell\'s World Championship Challenge (U).nes',
        'Nightmare on Elm Street, A (U).nes',
        'Nightshade (U).nes',
        'Ninja Crusaders (U).nes',
        'Ninja Gaiden (U) [!].nes',
        'Ninja Gaiden 2 - The Dark Sword of Chaos (U).nes',
        'Ninja Gaiden 3 - The Ancient Ship of Doom (U) [!].nes',
        'Ninja Kid (U).nes',
        'Nintendo World Cup (U).nes',
        'Nobunaga\'s Ambition (U).nes',
        'Nobunaga\'s Ambition 2 (U).nes',
        'North & South (U).nes',
        'official.nes',
        'Operation Secret Storm (U).nes',
        'Operation Wolf (U).nes',
        'Orb 3D (U).nes',
        'Othello (U).nes',
        'Overlord (U).nes',
        'P\'radikus Conflict, The (U).nes',
        'Pac-Mania (U).nes',
        'Palamedes (U).nes',
        'Panic Restaurant (U).nes',
        'Paperboy (U).nes',
        'Paperboy 2 (U).nes',
        'Peek-A-Boo Poker (UE) [!].nes',
        'Perfect Fit (U).nes',
        'Pesterminator - The Western Exterminator (U).nes',
        'Peter Pan & The Pirates (U).nes',
        'Phantom Fighter (U).nes',
        'Pictionary (U).nes',
        'Pinball (JU).nes',
        'Pinball Quest (U).nes',
        'Pinbot (U) [!].nes',
        'Pipe Dream (U).nes',
        'Pirates! (U).nes',
        'Platoon (U) (PRG1) [!].nes',
        'Popeye (JU) (PRG1) [!].nes',
        'POW - Prisoners of War (U).nes',
        'Power Blade (U) [!].nes',
        'Power Blade 2 (U).nes',
        'Power Pad Dance Aerobics (U).nes',
        'Power Punch 2 (U).nes',
        'Predator (U).nes',
        'Prince of Persia (U).nes',
        'Princess Tomato in Salad Kingdom (U).nes',
        'Pro Sport Hockey (U).nes',
        'Pro Wrestling (U) (PRG1) [!].nes',
        'Punch-Out!! (U).nes',
        'Punisher, The (U).nes',
        'Puss \'n Boots - Pero\'s Great Adventure (U).nes',
        'Puzznic (U).nes',
        'Q-bert (U).nes',
        'Qix (U).nes',
        'Quattro Adventure (U).nes',
        'Quattro Arcade (U).nes',
        'Quattro Sports (U).nes',
        'R.B.I. Baseball (U).nes',
        'R.B.I. Baseball 2 (U).nes',
        'R.B.I. Baseball 3 (U).nes',
        'R.C. Pro-Am (U) (PRG1).nes',
        'R.C. Pro-Am 2 (U).nes',
        'Race America (U).nes',
        'Racket Attack (U).nes',
        'Rad Racer (U).nes',
        'Rad Racer 2 (U) [!].nes',
        'Rad Racket - Deluxe Tennis II (U) [!].nes',
        'Raid 2020 (U) [!].nes',
        'Raid on Bungeling Bay (U).nes',
        'Rainbow Islands - The Story of Bubble Bobble 2 (U).nes',
        'Rally Bike (U).nes',
        'Rambo (U).nes',
        'Rampage (U).nes',
        'Rampart (U).nes',
        'Remote Control (U).nes',
        'Ren & Stimpy Show, The (U).nes',
        'Renegade (U).nes',
        'Rescue - The Embassy Mission (U).nes',
        'Ring King (U).nes',
        'River City Ransom (U).nes',
        'Road Runner (U).nes',
        'RoadBlasters (U).nes',
        'Robin Hood - Prince of Thieves (U).nes',
        'Robo Warrior (U).nes',
        'Robocop (U).nes',
        'Robocop 2 (U).nes',
        'Robocop 3 (U).nes',
        'Robodemons (U).nes',
        'Rock \'n\' Ball (U).nes',
        'Rocket Ranger (U) [!].nes',
        'Rocketeer, The (U).nes',
        'Rockin\' Kats (U) [!].nes',
        'Roger Clemens MVP Baseball (U).nes',
        'Rollerball (U).nes',
        'Rollerblade Racer (U).nes',
        'Rollergames (U) [!].nes',
        'Rolling Thunder (U).nes',
        'Romance of the Three Kingdoms (U).nes',
        'Romance of the Three Kingdoms II (U) [!].nes',
        'Roundball - 2-on-2 Challenge (U).nes',
        'Rush\'n Attack (U).nes',
        'Rygar (U).nes',
        'SCAT - Special Cybernetic Attack Team (U).nes',
        'Secret Scout (Unl).nes',
        'Section Z (U).nes',
        'Seicross (U).nes',
        'Sesame Street 123 (U).nes',
        'Sesame Street ABC (U).nes',
        'Sesame Street ABC - 123 (U).nes',
        'Sesame Street Countdown (U).nes',
        'Shadow of the Ninja (U).nes',
        'Shadowgate (U).nes',
        'Shatterhand (U).nes',
        'Shingen The Ruler (U).nes',
        'Shinobi (U).nes',
        'Shockwave (U).nes',
        'Shooting Range (U).nes',
        'Short Order - Eggsplode (U) [!].nes',
        'Side Pocket (U).nes',
        'Silent Assault (U).nes',
        'Silent Service (U).nes',
        'Silk Worm (U).nes',
        'Silver Surfer (U).nes',
        'Simpsons, The - Bart Vs. the Space Mutants (U).nes',
        'Simpsons, The - Bart Vs. the World (U).nes',
        'Simpsons, The - Bartman Meets Radioactive Man (U).nes',
        'Skate or Die 2 - The Search for Double Trouble (U).nes',
        'Skate or Die! (U).nes',
        'Ski or Die (U).nes',
        'Skull & Crossbones (U).nes',
        'Sky Kid (U).nes',
        'Sky Shark (U).nes',
        'Slalom (U).nes',
        'Smash T.V. (U) [!].nes',
        'Snake Rattle\'n Roll (U).nes',
        'Snake\'s Revenge (U).nes',
        'Snoopy\'s Silly Sports Spectacular (U).nes',
        'Snow Bros (U).nes',
        'Soccer (JU).nes',
        'Solar Jetman - Hunt for the Golden Warpship (U).nes',
        'Solitaire (U).nes',
        'Solomon\'s Key (U) [!].nes',
        'Solstice (U).nes',
        'Space Shuttle Project (U).nes',
        'Spelunker (U) [!].nes',
        'Spider-Man - Return of the Sinister Six (U) [!].nes',
        'Spiritual Warfare (U) (V6.1).nes',
        'Spot (U).nes',
        'Spy Hunter (U).nes',
        'Spy Vs Spy (U).nes',
        'Sqoon (U).nes',
        'Stack Up (Robot Block) (JU).nes',
        'Stadium Events (U) [!].nes',
        'Stanley - The Search for Dr. Livingston (U).nes',
        'Star Force (U).nes',
        'Star Soldier (U).nes',
        'Star Trek - 25th Anniversary (U).nes',
        'Star Trek - The Next Generation (U).nes',
        'Star Voyager (U).nes',
        'Star Wars (U).nes',
        'Star Wars - The Empire Strikes Back (U).nes',
        'Starship Hector (U).nes',
        'Startropics (U).nes',
        'Startropics 2 - Zoda\'s Revenge (U).nes',
        'Stealth ATF (U).nes',
        'Stinger (U).nes',
        'Stinger.nes',
        'Street Cop (U).nes',
        'Street Fighter 2010 (U).nes',
        'Strider (U).nes',
        'Stunt Kids (U).nes',
        'Sunday Funday (U).nes',
        'Super C (U) [!].nes',
        'Super Cars (U).nes',
        'Super Dodge Ball (U).nes',
        'Super Glove Ball (U).nes',
        'Super Jeopardy! (U).nes',
        'Super Mario Bros. + Duck Hunt (U).nes',
        'Super Mario Bros. + Duck Hunt + World Class Track Meet (U).nes',
        'Super Mario Bros. 2 (U) (PRG0) [!].nes',
        'Super Pitfall (U).nes',
        'Super Spike V\'Ball (U).nes',
        'Super Spike V\'Ball + Nintendo World Cup (U) [!].nes',
        'Super Sprint (U).nes',
        'Super Spy Hunter (U).nes',
        'Super Team Games (U).nes',
        'Superman (U).nes',
        'Swamp Thing (U) [!].nes',
        'Sword Master (U).nes',
        'Swords and Serpents (U).nes',
        'T&C 2 - Thrilla\'s Surfari (U).nes',
        'T&C Surf Design (U).nes',
        'Taboo - The Sixth Sense (U).nes',
        'Tag Team Wrestling (U).nes',
        'Tagin\' Dragon (U).nes',
        'TaleSpin (U).nes',
        'Target Renegade (U).nes',
        'Tecmo Baseball (U).nes',
        'Tecmo Bowl (U) (PRG1).nes',
        'Tecmo Cup - Soccer Game (U).nes',
        'Tecmo NBA Basketball (U).nes',
        'Tecmo Super Bowl (U).nes',
        'Tecmo World Wrestling (U).nes',
        'Teenage Mutant Ninja Turtles (U) [!].nes',
        'Teenage Mutant Ninja Turtles - Tournament Fighters (U).nes',
        'Teenage Mutant Ninja Turtles II - The Arcade Game (U) [!].nes',
        'Teenage Mutant Ninja Turtles III - The Manhattan Project (U).nes',
        'Terminator 2 - Judgment Day (U).nes',
        'Terminator, The (U).nes',
        'Terra Cresta (U).nes',
        'Three Stooges (U).nes',
        'Thunder & Lightning (U).nes',
        'Thunderbirds (U).nes',
        'Thundercade (U).nes',
        'Tiger-Heli (U).nes',
        'Tiles of Fate (U).nes',
        'Time Lord (U).nes',
        'Times of Lore (U).nes',
        'Tiny Toon Adventures (U).nes',
        'Tiny Toon Adventures 2 - Trouble in Wackyland (U).nes',
        'Tiny Toon Adventures Cartoon Workshop (U).nes',
        'To The Earth (U).nes',
        'Toki (U).nes',
        'Tom & Jerry and Tuffy (U).nes',
        'Tombs and Treasure (U).nes',
        'Toobin\' (U).nes',
        'Top Gun (U) (PRG1).nes',
        'Top Gun - The Second Mission (U).nes',
        'Top Players\' Tennis - Featuring Chris Evert & Ivan Lendl (U).nes',
        'Total Recall (U).nes',
        'Totally Rad (U).nes',
        'Touch Down Fever (U).nes',
        'Toxic Crusaders (U).nes',
        'Track & Field (U).nes',
        'Track & Field 2 (U).nes',
        'Transformers.nes',
        'Treasure Master (U).nes',
        'Trog (U).nes',
        'Trojan (U).nes',
        'Trolls on Treasure Island (U).nes',
        'Twin Cobra (U).nes',
        'Twin Eagle (U).nes',
        'Ultima - Exodus (U).nes',
        'Ultima - Quest of the Avatar (U).nes',
        'Ultima - Warriors of Destiny (U).nes',
        'Ultimate Air Combat (U).nes',
        'Ultimate Basketball (U).nes',
        'Ultimate League Soccer (U).nes',
        'Ultimate Stuntman (U).nes',
        'Uncharted Waters (U).nes',
        'Uninvited (U).nes',
        'Untouchables, The (U).nes',
        'Urban Champion (JU).nes',
        'Vegas Dream (U).nes',
        'Venice Beach Volleyball (U).nes',
        'Vice - Project Doom (U).nes',
        'Videomation (U).nes',
        'Vindicators (U).nes',
        'Volleyball (U).nes',
        'Wacky Races (U).nes',
        'Wall Street Kid (U).nes',
        'Wally Bear and the No Gang (U).nes',
        'Wario\'s Woods (U) [!].nes',
        'Wayne Gretzky Hockey (U).nes',
        'Wayne\'s World (U).nes',
        'WCW World Championship Wrestling (U).nes',
        'Werewolf - The Last Warrior (U).nes',
        'Wheel of Fortune (U) (PRG1) [!].nes',
        'Wheel of Fortune - Starring Vanna White (U).nes',
        'Wheel of Fortune Family Edition (U).nes',
        'Wheel of Fortune Junior Edition (U).nes',
        'Where in Time is Carmen Sandiego (U).nes',
        'Where\'s Waldo (U).nes',
        'Who Framed Roger Rabbit (U).nes',
        'Whomp\'Em (U).nes',
        'Widget (U).nes',
        'Wild Gunman (U) (PRG1) [!].nes',
        'Willow (U).nes',
        'Win, Lose or Draw (U).nes',
        'Winter Games (U).nes',
        'Wizardry - Proving Grounds of the Mad Overlord (U).nes',
        'Wizardry - The Knight of Diamonds (U).nes',
        'Wizards & Warriors (U).nes',
        'Wizards & Warriors 3 (U).nes',
        'Wolverine (U).nes',
        'World Champ (U) [!].nes',
        'World Games (U).nes',
        'Wrath of the Black Manta (U).nes',
        'Wrecking Crew (JUE) [t1].nes',
        'Wurm (U).nes',
        'WWF King of the Ring (U).nes',
        'WWF Steel Cage Challenge (U).nes',
        'WWF Wrestlemania (U).nes',
        'WWF Wrestlemania Challenge (U).nes',
        'Xenophobe (U).nes',
        'Xevious (U).nes',
        'Xexyz (U).nes',
        'Yo! Noid (U).nes',
        'Yo!Noid.nes',
        'Yoshi (U).nes',
        'Yoshi\'s Cookie (U).nes',
        'Young Indiana Jones Chronicles, The (U).nes',
        'Zanac (U).nes',
        'Zen Intergalactic Ninja (U).nes',
        'Zombie Nation (U).nes'
    )*/
}